board columns height modified
Umuzi-org/Tilde pull request #159
Opened 2021-08-26 11:58 UTC by Babalwa01

Related issues: [https://github.com/Umuzi-org/Tilde/issues/156]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos
![boardColumns](https://user-images.githubusercontent.com/52567054/130958688-219c5830-f9bd-4060-b3aa-4d2e9de32e0e.png)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-02 05:21 UTC, sheenarbw requested changes
This doesn't work. Try zooming in and out.

It needs to work on all screen sizes. Not just your personal screen size.  Where did you get 79vh from?  Where did you get 93% from?

Take a look here. I zoomed out quite a lot to make the problem obvious/. That blank space at the bottom should not be blank. The columns should reach the bottom of the screen
![Screenshot from 2021-09-02 07-19-13](https://user-images.githubusercontent.com/699166/131786330-ba95fce7-f216-4fb3-b1b0-d72d0cf18e19.png)

2021-09-07 23:07 UTC, Babalwa01 commented
![zoomOutView](https://user-images.githubusercontent.com/52567054/132421402-f5f54ba4-470f-4c30-9261-dfe24f246992.png)
![zoomInView](https://user-images.githubusercontent.com/52567054/132421435-7eb8dd2b-84f0-4202-b52f-a62fd569fab0.png)

2021-09-10 05:36 UTC, sheenarbw requested changes
You got it to work, but it's a bit untidy because the spacing doesn't match up

2021-09-10 05:36 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/Presentation.js
> +    height: "calc(100vh - 9rem)",
probably 6rem is more appropriate than 9 rem. Ideally the gap at the top should match the gap at the bottom. We want things to be tidy.

2021-09-20 07:41 UTC, sheenarbw commented
merged on my computer.

2021-09-20 07:41 UTC, closed without merging