#154 TeamsList and ReviewTrustList component api and redux wiring
Umuzi-org/Tilde pull request #162
Opened 2021-09-09 16:55 UTC by Babalwa01

Related issues: [https://github.com/Umuzi-org/Tilde/issues/154]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos
![dashboard_teams_and_reviewTrusts](https://user-images.githubusercontent.com/52567054/132729219-3c6b5c4a-f454-443b-ba70-1190006bb36b.png)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-13 14:56 UTC, sheenarbw requested changes
The file structure needs work.

Also, I see no mention of redux in the code you submitted in this PR.  But the PR title mentions redux. Is the title incorrect or is there code missing?

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/UserDetails/TeamsTable/Presentation.js
> +                    {
It looks like you have some extra brackets.

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/Dashboard/index.js
> +            <Typography>REVIEW TRUSTS</Typography>
Frontends are about communication. We need to choose words wisely. Dont just give things the same name as the api.

How about "You are a trusted reviewer for these cards:"

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/Dashboard/index.js
> +            <Typography>TEAMS</Typography>
WHY ARE YOU SHOUTING.

You could just use a heading component instead. Look at all the varients you can choose from: https://material-ui.com/components/typography/ 

It's also important to be consistent. Are there any other headings in Tilde that are in all caps? Nope. Not on the board, not on the actions  page, not on the login page...

Who will go update all those other headings to make them all capital letters?  Is that even necessary? Is there a reason why this page should have more capitalisation than the others?

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/Dashboard/index.js
> +import TeamsTable from "../UserDetails/TeamsTable/Presentation";
Please make use of the index.js files. If we just draw the PResentation components then none of the redux wiring will actually execute.

Rather:
```
import ReviewTrustTable from "../UserDetails/ReviewTrustTable";
import TeamsTable from "../UserDetails/TeamsTable";
```

If you just import the Presentation then the components wont actually work. They'll just be pictures without functionality. We need the Dashboard to function. We dont just want a bunch of empty tables.

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/Dashboard/index.js
> +        </Grid>
All this layout stuff should be in dashboard/presentation.js. 
Index.js is for smarts, not for layout.

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/Dashboard/index.js
> +import TeamsTable from "../UserDetails/TeamsTable/Presentation";
Of course these iomports should be in the Dashboard/Presentation.js file. This is not the place for layout

2021-09-13 14:56 UTC, sheenarbw commented on frontend/src/components/regions/Dashboard/Presentation.js
> +  return <div>TODO</div>
All layout should go in here. 
Please import child components and make sure this Presentation file lays them out correctly.

2021-10-08 05:17 UTC, sheenarbw requested changes
You included a bunch of weird stuff in your PR. Please remove the unnecessary things.

2021-10-08 05:17 UTC, sheenarbw commented on frontend/src/components/regions/UserDetails/TeamsTable/redux/operations.js
> +    openTeamsTable: ({ userId }) =>
What is this for? I dont think the teams table is a modal.

2021-10-24 10:40 UTC, babalwa-mbolekwa commented
![teamsDashboard](https://user-images.githubusercontent.com/52567054/138888219-66ce29e4-9624-4c5f-b0d2-5d870edcafd1.png)

2021-10-26 06:58 UTC, Vuyisanani reviewed
Hi @Babalwa01 

Can you please make sure you have the requested changes resolved, mark them resolve or they should be outdated

2021-10-26 07:01 UTC, Vuyisanani reviewed
Don't you also have to write unit tests?

2021-10-26 11:09 UTC, babalwa-mbolekwa commented
> You included a bunch of weird stuff in your PR. Please remove the unnecessary things.

attended to changes

2021-10-26 11:10 UTC, babalwa-mbolekwa commented on frontend/src/components/regions/UserDetails/TeamsTable/redux/operations.js
> +    openTeamsTable: ({ userId }) =>
> What is this for? I dont think the teams table is a modal.

attended to changes requested

2021-10-26 11:13 UTC, babalwa-mbolekwa commented
> Don't you also have to write unit tests?

@Vuyisanani not quite sure how I can structure them for this ticket. Kindly assist with the approach

2021-10-27 07:02 UTC, Vuyisanani approved these changes

2021-10-28 06:32 UTC, sheenarbw approved these changes

2021-10-28 06:32 UTC, merged