Email password login update
Umuzi-org/Tilde pull request #167
Opened 2021-09-13 22:37 UTC by Sbonelo01

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

The idea is to keep things simple and minimalistic

![Screenshot from 2021-09-14 00-24-27](https://user-images.githubusercontent.com/37469171/133165313-a47da9c3-1c76-4183-a945-3ffaca0f49d3.png)

2021-09-14 08:52 UTC, Babalwa01 requested changes
Hey Sbonelo the UI looks good on storybook but can be improved:
- Please also include and use the props that were originally used.
- Please also keep the alerts and the heading that was used, also take note of the conditions used with the alerts
- I get this error when running it on Tilde localhost `./src/components/regions/Login/Presentation.js`
`Attempted import error: 'createTheme' is not exported from '@material-ui/core/styles'.` please check if **createTheme** is imported correctly.

2021-09-14 17:00 UTC, Babalwa01 submitted a review, later dismissed

2021-09-20 07:11 UTC, sheenarbw requested changes
Why not just add the form to the login page that we already have? Why do we need 2 seperate login pages? If we allowed login with Github or Rocketchat then would we have 4 login pages?

We could have a page that has the form and also has a "login with google" button.  Why not?

2021-09-20 07:21 UTC, Sbonelo01 commented
> Why not just add the form to the login page that we already have? Why do we need 2 seperate login pages? If we allowed login with Github or Rocketchat then would we have 4 login pages?
> 
> We could have a page that has the form and also has a "login with google" button. Why not?

@sheenarbw  That makes sense. Looking at the new updated Prioritised backlog frontend issues I was thinking of creating separate components as stories and once you approve how they look, we can glue everything together. I could be thinking about this in the wrong way?

2021-09-20 08:03 UTC, sheenarbw commented
@Sbonelo01 
Please always update the code that is meant to be updated.  If we do it your way then it's at least double the work. Imagine:

1. You write a login form frontned and a story for it (that takes some doing) Note that we will need to delete all these files later.
2. I tell you it's missing the "login with google" button so you add that in and eventuially get it looking good.
3. Now it looks perfect so you update the existing login page with the new layout. You also make sure that the story that illustrates the final corect login page. Unfortunately the code you wrote wasn't designed to be integrated into the existing machine so this process is error prone
4. delete everything you did from 1 since it has now been copy pasted into the correct place. 
5. Get another code review from me - making me do a repetitive job
6. I find that your code isa actually incompatable with what is in place or that you forgot to purge all the useless and unintegratable code. You are likely to make mistakes when actually wtriting code that is meant to be integrated with what is in place. You have also increased the chance of human error significantly
7. You clean up and eventually we get to merge. 

The better way:
1. Updaste the page you were meant to update. Work on the story you were meant to work on. Put things in the final place. Dont put the code in arbitrary locations. Dont write files that are just meant to be deleted.
2. Ask for a code review
3. I tell you about any integration problems and you fix those
4. get to merge smoothly

2021-09-21 18:01 UTC, Sbonelo01 commented
![Screenshot from 2021-09-21 19-55-34](https://user-images.githubusercontent.com/37469171/134223469-70ef6c0f-124a-4b05-886f-19a6ef873425.png)

2021-09-22 10:51 UTC, Babalwa01 requested changes
Awesome work Sbonelo! 
Please also put the _Please log in_ heading and also remove the `{ useState }`  import that's causing a warning on the Login Presentation.js file

2021-09-23 08:12 UTC, Babalwa01 submitted a review, later dismissed
Well done Sbonelo!

2021-09-27 10:13 UTC, sheenarbw requested changes
I haven't reviewed everything. There is at least one thing to clean up here

2021-09-27 10:13 UTC, sheenarbw commented on frontend/src/stories/Login.stories.js.orig
> +import LoginForm from "../components/regions/Login/LoginForm"
please remove this file.

When you do a self-review you should always check that there aren't any weird extra files that slipped into the PR.

2021-09-28 03:54 UTC, Babalwa01 requested changes
Very good work Sbonelo. Please also add the needed props to the Login story, e.g :
since the LoginForm component makes use of `loading`, `error`, `handleLoginWithGoogle` then you can create your story like:
`export const Primary = (args) => <LoginForm {...args} />`
`Primary.args = {`
`loading: false,`
`error: "",`
`handleLoginWithGoogle: () => {},`
`}`
you'll then be able to see the props it uses in the bottom "Controls" section on storybook
If a prop is a:
- boolean: set to false
- function: set it to an empty function
- string: empty string
- object: you can use the ones from `src/stories/fixtures` or create a different sample object within the story file
- array: an empty array

2021-09-29 07:00 UTC, Babalwa01 approved these changes
Well done Sbonelo!

2021-09-30 14:14 UTC, sheenarbw approved these changes

2021-09-30 14:15 UTC, merged