Change password page
Umuzi-org/Tilde pull request #195
Opened 2021-09-23 19:41 UTC by Sbonelo01

Related issues: [https://github.com/Umuzi-org/Tilde/issues/172]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

![Screenshot from 2021-09-23 21-32-47](https://user-images.githubusercontent.com/37469171/134572966-59e7c8c2-bfbc-45dd-97dc-f314f1971426.png)

2021-09-27 06:42 UTC, sheenarbw requested changes
It's hard to see what you are trying to achieve here. 

The title of the PR is change password. But you are implemnenting a form that looks like it is for somethig differewnt (but related).

It would be useful if you filled in the "linked issue " firld on this PR.
Please always fill in the "linkede issue" field on all your PRs

2021-09-27 06:42 UTC, sheenarbw commented on frontend/src/components/regions/Login/ChangePassword/Presentation.js
> +        <Button type="submit" variant="contained" color="primary" className={classes.button}>
Let's keep button styling consistent.

Also, it's my understanding that this PR is for users who want to change their passwords. So if I log in and I decide to change my password I can navigate to this page. So this page looks incorrect. Generally ChangePAssword forms have 3 fields:
- current password
- new password 
- confirm password

Reset password functionality is generally for users who have forgotten thewir passwords and need to go through a mission to get it updated. They enter their email address, then get an email with a special token, then fill in another form.

2021-09-27 20:05 UTC, Sbonelo01 commented
The aim is to keep the button width the same as the text field width

![Screenshot from 2021-09-27 21-56-15](https://user-images.githubusercontent.com/37469171/134977243-b68ddae3-acc5-45d4-b2fb-0f4b97439f60.png)

2021-09-28 04:15 UTC, Babalwa01 approved these changes

2021-09-30 14:12 UTC, sheenarbw approved these changes

2021-09-30 14:12 UTC, merged