Reset password page story
Umuzi-org/Tilde pull request #197
Opened 2021-09-28 15:45 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-29 07:38 UTC, Babalwa01 requested changes
Good job Kaleem. 
Please see Sbonelo's pull request [https://github.com/Umuzi-org/Tilde/pull/194](https://github.com/Umuzi-org/Tilde/pull/194) and its latest screenshot here [https://user-images.githubusercontent.com/37469171/134504325-a7822c4e-e297-4945-b52f-f14537fcfa71.png](https://user-images.githubusercontent.com/37469171/134504325-a7822c4e-e297-4945-b52f-f14537fcfa71.png)
it would be good to have the same styling for consistency since the features are related: note the alert message and heading styles.

2021-09-30 11:45 UTC, Vuyisanani commented
Hi @kaleem99 

Can you please first check  the **I solemnly swear that**: checkboxes to be sure you have tested  your code,
Also do add the screenshot of your changes

2021-09-30 14:12 UTC, sheenarbw requested changes
Why are there changes to package-lock? Are those changes needed?

And can you please always attach a screenshot when you make a PR that has a visual element? It makes it much easier if I can picture what you are doing without needing to download everything.

2021-09-30 14:12 UTC, sheenarbw commented on frontend/src/components/regions/ResetPassword/Presentation.js
> +          style={textInput}
please look at how other components are styled. When in doubt be consistent.

Do a Ctrl+Shift+F search for useStyle

2021-10-01 15:43 UTC, kaleem99 commented
![Tilde](https://user-images.githubusercontent.com/62307224/135649073-f7a743dc-ba05-4f56-bc34-2e782c024df1.PNG)

2021-10-02 08:59 UTC, MichaelCurrin commented on frontend/package-lock.json
> +}
This change should not have been committed. It removes a trailing newline from a file which otherwise wasn't edited.

2021-10-02 09:01 UTC, MichaelCurrin commented on frontend/package-lock.json
> +}
I see the red warning marker in other files here too. Set up your IDE settings to add the trailing newline on save and you'll be sorted.

2021-10-02 09:05 UTC, MichaelCurrin commented on frontend/src/components/regions/ResetPassword/index.js
> +import React from "react";
Can this index.js file be deleted? It isn't imported anywhere.

2021-10-02 09:07 UTC, MichaelCurrin commented on frontend/src/components/regions/ResetPassword/index.js
> +import React from "react";
Or is this needed by Storybook?

2021-10-03 21:05 UTC, Sbonelo01 requested changes
Hey @kaleem99 , Please pay attention to the font-family that you are using in your PR.

Please check how I have used the Typography component here: https://github.com/Umuzi-org/Tilde/pull/194 and try to keep it in line with the rest of the project.

Please also have a look at the width of the Alert from PR #194 

Also, please make the width of the button similar to the width of the input field.

Please remove the `babalwa.mbolekwa@umuzi.org` text.

2021-10-04 19:01 UTC, kaleem99 commented on frontend/src/components/regions/ResetPassword/index.js
> +import React from "react";
its needed by storybook

2021-10-04 19:51 UTC, kaleem99 commented
![Tilde2](https://user-images.githubusercontent.com/62307224/135915314-f2b52be8-7ab1-4aae-9d9a-f336386881a2.PNG)

2021-10-05 06:25 UTC, Vuyisanani commented
Hi @kaleem99 

How does a user navigate back to the Home page?

2021-10-06 13:54 UTC, Sbonelo01 commented
> Hi @kaleem99
> 
> How does a user navigate back to the Home page?

@kaleem99 Please note

2021-10-06 16:12 UTC, kaleem99 commented
> > Hi @kaleem99
> > How does a user navigate back to the Home page?
> 
> @kaleem99 Please note

The instructions doesn't specify that there should be a button or a link that directs/navigates the user to the home page.

2021-10-06 16:26 UTC, Sbonelo01 commented
The only issue I have is with the alignment of the text in the Alert component ( can you please keep it like so : https://github.com/Umuzi-org/Tilde/pull/194 ). And should that `babalwa.mbolekwa@umuzi.org` email be there?

All else looks okay

2021-10-11 06:35 UTC, kaleem99 commented
> The only issue I have is with the alignment of the text in the Alert component ( can you please keep it like so : #194 ). And should that `babalwa.mbolekwa@umuzi.org` email be there?
> 
> All else looks okay

The email should be there since the user.json file contains the current user's email address and information, we using that information to test the front end, the current user's information is Babalwas tilde details.

2021-10-12 05:58 UTC, Vuyisanani approved these changes

2021-10-12 06:56 UTC, babalwa-mbolekwa approved these changes

2021-10-12 12:25 UTC, kaleem99 commented
![Uploading Tilde3.PNG…]()

2021-10-19 05:56 UTC, Vuyisanani reviewed
Please make sure you do not commit the packagelock.json file

Also, make sure your base branch is protected/feat/email-password-login , not develop

2021-10-19 05:56 UTC, Vuyisanani commented on frontend/src/components/regions/ResetPassword/Presentation.js
> +        color="primary"
Since you are only using the buttonStyle class here, you can add the color to the * buttonStyle**

2021-10-20 19:36 UTC, Sbonelo01 requested changes
Hi there Kaleem, It seems like the `package-lock` is still being committed here

2021-10-21 22:53 UTC, Vuyisanani approved these changes

2021-10-22 06:37 UTC, Sbonelo01 approved these changes

2021-10-25 07:06 UTC, sheenarbw requested changes
Please don't delete package-lock.json.

2021-10-25 07:06 UTC, sheenarbw commented on frontend/package-lock.json
> +}
@kaleem99 can you  please removew this file from your PR? I'm not sure why it's here.

2021-10-25 14:58 UTC, sheenarbw commented on frontend/src/components/regions/ResetPassword/index.js
> +import React from "react";
@MichaelCurrin thanks for your input :) 

We are building out all the password stuff piece by piece. So sopme stuff will seem a little out of place until it is complete

2021-10-26 06:22 UTC, Vuyisanani approved these changes

2021-10-26 07:09 UTC, sheenarbw approved these changes

2021-10-26 07:09 UTC, merged