admin_panel_functionality_to_deactivate_inactive_users/ #110
Umuzi-org/Tilde pull request #203
Opened 2021-10-08 15:27 UTC by EckardBerry

…ch develop and then opened new PR with requested changes done

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)
- Closed old PR and deleted old branch, created new branch from 'develop' branch and opened new PR with requested changes
- Made some changes to core.admin, added a function there called "deactivate_team_members"
- Created a new test in core.tests, it is called "test_admin_functionality_make_team_members_inactive.py"

## Screenshots/videos

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-10-12 08:17 UTC, sheenarbw commented
This doesn't seem to be linked to an issue

2021-10-14 05:24 UTC, TheAbstract approved these changes

2021-10-15 05:02 UTC, Vuyisanani approved these changes

2021-10-18 09:20 UTC, sheenarbw requested changes
Getting there... 

This is close but there are a few issues. Some naming things and clean code things. 

Also, you removed my second favorite search bar. Not sure why.

2021-10-18 09:20 UTC, sheenarbw commented on backend/core/admin.py
> -    search_fields = ["name"]
Why did you take away search? I use that very often. Being able to search saves me time. Please put it back.

2021-10-18 09:20 UTC, sheenarbw commented on backend/core/tests/test_admin_functionality_make_team_members_inactive.py
> +class TestMakeTeamMembersInactiveForInactiveTeams(TestCase):
This test name implies that this functionality should only work for teams that are inactive. But I dont think that the team has to be inactive for this stuff to work.

2021-10-18 09:20 UTC, sheenarbw commented on backend/core/admin.py
> +def deactivate_team_members(TeamAdminInstance, request, queryset: object):
Take a look here: https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/#actions-as-modeladmin-methods 

This function is very tightly coupled with the Team model, it would make sense to put it inside the TeamAdmin class. We wont use it anywhere else

2021-10-18 09:20 UTC, sheenarbw commented on backend/core/tests/test_admin_functionality_make_team_members_inactive.py
> +class TestMakeTeamMembersInactiveForInactiveTeams(TestCase):
Meaning - if the team is active then this should still work. We dont need to add extra restrictions.

2021-10-18 10:20 UTC, EckardBerry commented on backend/core/admin.py
> -    search_fields = ["name"]
Sorry, I put it back.

2021-10-18 10:21 UTC, EckardBerry commented on backend/core/tests/test_admin_functionality_make_team_members_inactive.py
> +class TestMakeTeamMembersInactiveForInactiveTeams(TestCase):
Test name changed to reflect the fact that the function will work for both active and inactive teams.

2021-10-18 12:04 UTC, EckardBerry commented on backend/core/admin.py
> +def deactivate_team_members(TeamAdminInstance, request, queryset: object):
I had a look at this when I started this ticket, seems there is an issue with importing @admin.action decorator.  I can import it just fine from from "django.contrib.admin import action" but during runtime I get an error that says you can't import action from admin.  The function is now inside the class though.

2021-10-20 05:30 UTC, TheAbstract commented on backend/core/tests/test_admin_functionality_make_team_members_inactive.py
> +class TestMakeTeamMembersInactiveForATeamOrTeams(TestCase):
Is the `OrTeams` necessary? Can the operation be done for multiple teams simultaneously?

2021-10-20 09:36 UTC, EckardBerry commented on backend/core/tests/test_admin_functionality_make_team_members_inactive.py
> +class TestMakeTeamMembersInactiveForATeamOrTeams(TestCase):
Hi yes, the operation can be done for one team or many teams but not simultaneously.  So either you make all members of a team inactive or you select a bunch of teams and then each member of each team will be made inactive.  I will remove the 'OrTeams' if it causes confusion?

2021-10-20 13:34 UTC, TheAbstract approved these changes

2021-10-21 14:08 UTC, sheenarbw approved these changes

2021-10-21 14:08 UTC, merged