Email password login UI/UX update
Umuzi-org/Tilde pull request #207
Opened 2021-10-17 23:05 UTC by Sbonelo01

Related issues: [https://github.com/Umuzi-org/Tilde/issues/205]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

@Vuyisanani , I have implemented the changes that you have requested - everything except the buttons. I think we should keep the current button shapes.

![Screenshot from 2021-10-18 00-32-39](https://user-images.githubusercontent.com/37469171/137648121-26ef96e0-e866-45c9-add9-07d6194af8dc.png)

2021-10-19 08:55 UTC, babalwa-mbolekwa requested changes
Hey Sbonelo 
- please fix the font family of `Forgot Password?` to be the same as the other fonts.
- please also reduce the space between the Tick box and the `Remember me` text so that it shows they are grouped
![login](https://user-images.githubusercontent.com/52567054/137876498-6ca42472-0ce1-420a-8121-330679246d68.png)

Everything else LGTM!

2021-10-20 19:38 UTC, Sbonelo01 commented
![Screenshot from 2021-10-20 21-37-08](https://user-images.githubusercontent.com/37469171/138160369-7b835ef1-b920-43b5-8732-726065ddbf00.png)

2021-10-21 13:06 UTC, babalwa-mbolekwa submitted a review, later dismissed

2021-10-22 16:50 UTC, kaleem99 submitted a review, later dismissed

2021-10-25 07:47 UTC, Vuyisanani submitted a review, later dismissed

2021-10-25 07:47 UTC, Vuyisanani commented on frontend/src/components/regions/Login/Presentation.js
> +          href="#"
Does this link redirects to anywhere?

2021-10-25 07:47 UTC, Vuyisanani commented on frontend/src/components/regions/Login/Presentation.js
> +          style={{
I think would be better to have the Link styles in a class

2021-10-25 07:47 UTC, Vuyisanani commented on frontend/src/components/regions/Login/Presentation.js
> +              style={{ marginLeft: "0", width: "20px", padding: 0 }}
Can we also just add these in a class

2021-10-26 20:48 UTC, Sbonelo01 commented on frontend/src/components/regions/Login/Presentation.js
> +          href="#"
Hi there @Vuyisanani , I think there is/was an issue specifically for this

2021-10-26 20:48 UTC, Sbonelo01 commented on frontend/src/components/regions/Login/Presentation.js
> +          style={{
sorted

2021-10-26 20:48 UTC, Sbonelo01 commented on frontend/src/components/regions/Login/Presentation.js
> +              style={{ marginLeft: "0", width: "20px", padding: 0 }}
sorted

2021-10-27 07:12 UTC, Vuyisanani approved these changes

2021-10-28 12:49 UTC, Vuyisanani submitted a review, later dismissed

2021-10-28 12:49 UTC, Vuyisanani commented on frontend/src/components/regions/Login/Presentation.js
> +          href="#"
Oh cool, then a new issue will need to be created for this.

2021-10-29 06:29 UTC, Babalwa01 submitted a review, later dismissed

2021-11-02 05:22 UTC, sheenarbw requested changes
Please overcome the merge conflicts. This can't be merged

2021-11-08 08:45 UTC, Vuyisanani commented
Please do not forget to add e.preventDefault()

2021-11-09 06:25 UTC, Vuyisanani approved these changes

2021-11-09 07:30 UTC, sheenarbw approved these changes

2021-11-09 07:31 UTC, merged