Has card been reviewed
Umuzi-org/Tilde pull request #215
Opened 2021-10-27 08:10 UTC by Sbonelo01

Related issues: [https://github.com/Umuzi-org/Tilde/issues/144]

## Description: 
**This small PR seeks to get confirmation whether the icon is placed in the correct place or not, need feedback from  @Vuyisanani as per the issue details. The rest of the code is still under construction.**

What are you up to? Fill us in :)

## Screenshots/videos

![Screenshot from 2021-10-27 08-30-10](https://user-images.githubusercontent.com/37469171/139026425-988bfd12-6cae-4662-8437-91fac8c3525e.png)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-27 21:50 UTC, Vuyisanani commented on frontend/src/components/regions/AgileBoard/AgileCard/Presentation.js
> +          color="primary"
Instead of introducing a new colour to the Card, can you rather consider using this color: #3f51b5;

2021-10-27 21:52 UTC, Vuyisanani commented
The check box,  position and size is fine, but just the colour,  make it be like the one below, #3f51b5;
<img width="46" alt="Screenshot 2021-10-27 at 23 52 02" src="https://user-images.githubusercontent.com/35369692/139152689-3107b016-a773-4b28-82d2-3458ab64105a.png">

2021-11-03 06:06 UTC, Vuyisanani approved these changes

2021-11-03 06:07 UTC, Vuyisanani commented on frontend/src/components/regions/AgileBoard/AgileCard/Presentation.js
> +          color="primary"
I see this is the same colour when pulled this on my branch :)

2021-11-10 09:04 UTC, Babalwa01 requested changes
Hey Sbonelo. The UI looks great and all tests pass, but the box is not ticked when the viewed user's ID is part of the IDs in the `usersThatReviewedSinceLastReviewRequest` list from Storybook. could you please fix that part. 
- The card titles are also repeated when the card is not in the review column, could you please fix them too:
![titles](https://user-images.githubusercontent.com/52567054/141083484-ba6492e8-683e-4e4e-bf54-a365511d590c.png)

2021-11-10 16:39 UTC, Sbonelo01 commented
Hey @Babalwa01, It does change.

This is the card when the viewed users id is not in the reviewers list:

![Screenshot from 2021-11-10 18-34-07](https://user-images.githubusercontent.com/37469171/141154493-23922d79-b2ea-47eb-902c-dface3a04084.png)

and this is the card when the viewed user id is found in the card:

![Screenshot from 2021-11-10 18-35-25](https://user-images.githubusercontent.com/37469171/141154622-4254f654-6e87-41f8-a11c-ef2ad2d4806c.png)

The code relies on data change here (the highlighted part) : 

![Screenshot from 2021-11-10 18-35-50](https://user-images.githubusercontent.com/37469171/141154717-27ff1d0e-7223-4429-aae7-c54652617f6f.png)

2021-11-11 17:53 UTC, Babalwa01 approved these changes
Well done Sbonelo!

2021-11-15 04:04 UTC, sheenarbw requested changes
It looks like it works but the code follows a few bad practices. 

Good names and single purpose functions make code a lot clearer. 

AgileCard Presentation directly calls checkIfCardIsInReviewColumn and showCheckedBox. 
Then ShowCheckedBox calls checkIfCardIsInReviewColumn and checkIfUserIdExistsInReviewers 

That is a complicated way to solve a simple problem. 

AgileCard Presentation  should call one function to know if it should draw the checkbox or not and another function to decide if the box should be checked. These 2 functions shouldn't know about each other. You only need 2 functions and they are both very simple and independent. 

Please work on making your code as simple as possible. Otherwise when you get a complicated problem to solve it's going to be really a lot of spagetti.

2021-11-15 04:04 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/AgileCard/AgileCard.test.js
> +test("showCheckedBox should return false if the card is not in the review column", () => {
The checkbox should be shown if the card is in the review column. This makes it look like you only want to show the checkbox if the user has already reviewed the card. 

Names are important. 

And also, how do you know we wont use other checkboxes later on? And maybe we'll decide to use a different way to visualise this stuff later on instreead of a checkbox.  Why does your function even need to know that it has anything to do with a checkbox? 

How about calling the function: `userReviewedSinceLastReviewRequest`, it would return true oif the user did review the card since the last review request. See how the function name fully describes what the function actually does?

2021-11-15 04:04 UTC, sheenarbw commented on frontend/src/stories/fixtures/agileCard.json
> +    "id": 130508,
Can you please avoid changing fixtures unless you need to? There are all sorts of changes here that are irrelevent to your code.  Other people use these fixtures, did you make sure you didn't break any stories?

2021-11-15 04:04 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/AgileCard/utils.js
> +export function showCheckedBox({ viewedUser, card }) {
Is this unction supposed to decide if the checkbox should be shown or not? OR is it supposed to decide if the checkbox should be checked or not? 

It should do only one of these things. Not bothe of these things.

2021-11-15 13:36 UTC, sheenarbw approved these changes

2021-11-15 13:36 UTC, merged