Card status widget
Umuzi-org/Tilde pull request #230
Opened 2021-11-03 19:00 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-04 06:20 UTC, kaleem99 commented
![Tilde-card-status-widget](https://user-images.githubusercontent.com/62307224/140267215-93389e6e-1ab8-44f9-a25e-aca1811e7c76.JPG)

2021-11-04 07:03 UTC, sheenarbw requested changes
Hmm this works but it's not DRY

2021-11-04 07:03 UTC, sheenarbw commented on frontend/src/components/regions/CardDetails/Presentation.js
> +    [IN_PROGRESS]: { ...card, backgroundColor: green[400] },
Are you sure this is DRY? It looks very familiar. 

If a piece of code needs to be reused then copy-paste usually isn't the best bet.  Rather make a little widget we can use  in multiple places

2021-11-08 20:20 UTC, Sbonelo01 requested changes
Looking good @kaleem99 . Can you please work on the padding of the chip? Align it nicely with the ones above it

2021-11-09 06:09 UTC, Babalwa01 commented
hey @kaleem99 can you also please attach the screenshot of the latest updated work

2021-11-09 11:29 UTC, kaleem99 commented
<img width="932" alt="Screenshot 2021-11-09 132638" src="https://user-images.githubusercontent.com/62307224/140916283-0dcab4e9-cbd5-47e4-834b-ccaaaba3b842.png">

2021-11-10 09:24 UTC, Babalwa01 requested changes
hey Kaleem well done. Looks good on stoybook, on the localhost it says `Loading...` and doesn't show anything on the board. Could you please double check if the Presentation files are correctly written

2021-11-11 18:23 UTC, Babalwa01 approved these changes
Well done Kaleem! It looks good on storybook. I couldn't check on the localhost because it displays `Loading...`

2021-11-11 22:43 UTC, Vuyisanani approved these changes

2021-11-12 14:00 UTC, Sbonelo01 commented
If the widget is supposed to be positioned like that, then all is good

2021-11-15 03:46 UTC, sheenarbw requested changes
This works but it has a few weird things slipping in. Some stuff is just a bit messy. And also it would be good to learn about what html tables do. Materiual ui tables are conceptually very similar to standard html <tables>. You shouldn't just use table cells oputside a table.

2021-11-15 03:46 UTC, sheenarbw commented on frontend/src/stories/fixtures/repoProjectCard.json
> +  "status": "IP",
Can you try not to change fixtures unless you absolutely need to? Sometimes they are set up in a specific way for a reason

2021-11-15 03:46 UTC, sheenarbw commented on frontend/src/components/regions/CardDetails/Presentation.js
> +        </TableCell>
It's a little odd to use a tablecell here. Where is the rest of the table?  Dont you want to use Grid things rather?

2021-11-15 03:46 UTC, sheenarbw commented on frontend/src/components/regions/GroupCardSummary/CellContent/Presentation.js
>                  <Paper className={classes[card.status]} variant="outlined">
Are you sure this Paper shopuld still be here? It looks like it is a repeat of what is inside frontend/src/components/widgets/CardStatusChip.js and the classname doesn't make sense.

There are a lot of people on the team, it's best if everyone does their bit to keep things tidy.

2021-11-15 03:46 UTC, sheenarbw commented on frontend/src/components/widgets/CardStatusChip.js
> +      <Paper className={classes[card.status]} variant="outlined">
The alignment here is a little strange. Can you please try to keep things tidy?

2021-11-16 06:09 UTC, kaleem99 commented
<img width="949" alt="card-status" src="https://user-images.githubusercontent.com/62307224/141930586-a1190363-b967-4d3e-8a9a-f9d137dee841.png">

2021-11-16 06:10 UTC, kaleem99 commented
<img width="936" alt="card-status2" src="https://user-images.githubusercontent.com/62307224/141930602-cc4c8722-182e-4fce-97ed-ad20bee92ed4.png">

2021-11-16 06:42 UTC, Babalwa01 requested changes
Could you please also double check the imports here also. It displays this error on the frontend
![errorscolor](https://user-images.githubusercontent.com/52567054/141934596-a07f9c88-2d5b-4913-9b43-57477f74cac5.png)

2021-11-16 11:17 UTC, kaleem99 commented
<img width="946" alt="card-status" src="https://user-images.githubusercontent.com/62307224/141975877-0ed1aada-51f5-4988-af7a-e9e8645d72cc.png">

2021-11-16 11:17 UTC, kaleem99 commented
<img width="949" alt="card-status2" src="https://user-images.githubusercontent.com/62307224/141975901-ea009179-0ce3-426b-9879-04a96f08e0de.png">

2021-11-16 11:18 UTC, Babalwa01 approved these changes

2021-11-16 13:02 UTC, Sbonelo01 approved these changes
Looks good

2021-11-17 17:35 UTC, Vuyisanani approved these changes

2021-11-22 06:22 UTC, sheenarbw approved these changes
Weeee

2021-11-22 06:22 UTC, merged