Polish for user stats per week/231
Umuzi-org/Tilde pull request #247
Opened 2021-11-15 11:53 UTC by EckardBerry

Related issues: [please specify]

1. I've made some changes to the UserStatsPerWeek Serializer, it is now called "UserDetailedStatsSerializer".
2. I've added extra functionality to UserDetailedStatsSerializer, functionality such as how many cards are currently blocked, and how many cards are ready to be started.
3. I've added some tests for the new functionality, the tests live inside "test_UserDetailedStatsAPI.py" which is located in backend/curriculum_tracking/tests.  The test file has already been renamed in accordance with the renaming of the serializer, hence why the new file name is "test_UserDetailedStatsAPI".

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-11-15 13:35 UTC, sheenarbw requested changes
Looks like it works, but it can be done slightly more simply

2021-11-15 13:35 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            Q(status=models.AgileCard.BLOCKED) & Q(assignees=user.id)
This works, but why the added complexity? If you want to achieve an `and` then you can just chain multiple filters together (like you did with the other ones).

Q is useful for or, not and things that are more llke boolean algebra.  Always remember the principle of KISS.

2021-11-17 10:42 UTC, TheAbstract approved these changes
Feedback implemented.

2021-11-18 11:00 UTC, sheenarbw approved these changes

2021-11-18 11:00 UTC, merged