initial commit Aligned Button and title
Umuzi-org/Tilde pull request #248
Opened 2021-11-15 18:14 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-16 06:03 UTC, kaleem99 commented
<img width="951" alt="align-title" src="https://user-images.githubusercontent.com/62307224/141929906-52cfc16a-cf14-4be5-8882-83466f30c240.png">

2021-11-16 06:03 UTC, kaleem99 commented
<img width="946" alt="aligned-title2" src="https://user-images.githubusercontent.com/62307224/141929918-0cd839a5-883d-4c60-8583-c29902cf5fdc.png">

2021-11-16 06:37 UTC, Babalwa01 requested changes
Hey Kaleem could you please double check if you have imported correctly from material UI. I got this errors on the frontend
![errors](https://user-images.githubusercontent.com/52567054/141933869-26476fd3-1389-4f46-804c-cb79670636f7.png)

2021-11-16 07:49 UTC, Vuyisanani requested changes
Hi @kaleem99 

Great work so far, just one small thing for consistency, can you add a margin/padding to the titles here as well, just to align them with the email addresses.

![Screenshot 2021-11-16 at 09 46 42](https://user-images.githubusercontent.com/35369692/141942673-5c0f691e-e83c-4eba-bc27-af5ff959af34.png)


![Screenshot 2021-11-16 at 09 42 45](https://user-images.githubusercontent.com/35369692/141942710-eadedd4d-f0c8-43fd-ac6d-2d351f89ee7f.png)

2021-11-16 16:13 UTC, kaleem99 commented
<img width="956" alt="align" src="https://user-images.githubusercontent.com/62307224/142022700-731fc2b8-3a0f-4022-8a2d-02f645f6a8a5.png">

2021-11-17 17:32 UTC, Vuyisanani approved these changes

2021-11-22 06:08 UTC, sheenarbw requested changes
Looks good but there are a few little things

2021-11-22 06:08 UTC, sheenarbw commented on frontend/src/components/widgets/BaseButtonLink.js
> +  input: {
I'm not sure what input is doe. You don't seem to use it.

And why is the other class named title? That's an odd name for a button's class.

And what happens if we put the button underneath another element that hes marginBottom set? now other elements needs to be aware of the margins set up in this file. I'm not sure it makes sense to have the classes here at all.

2021-11-22 06:08 UTC, sheenarbw commented on frontend/src/components/regions/UserDetails/TeamsTable/Presentation.js
> +            <Typography variant="h6" component="h2" style={{ width: "90%" }}>
why do we sometimes use classes and sometimes use inline styles?

2021-11-23 08:35 UTC, sheenarbw requested changes
Some changes weren't addressed before. 

And styles are quite spegitti like. Please look into KISS and the principle of least privelage. DRY code should never ever imply spagetti code

2021-11-23 08:35 UTC, sheenarbw commented on frontend/src/components/widgets/LinkToUserBoard.js
> +import { useStyles } from "./BaseButtonLink";
Please rather style things in place. Spagetti styling makes things hard to reason about. 

Importing and exporting styles from all over the place makes it hard to know what things do.

If styles are used in 1 component put them in that component.

Global styles should not be defined in strange littel components.

2021-11-25 11:02 UTC, Babalwa01 approved these changes

2021-11-25 11:06 UTC, Sbonelo01 approved these changes

2021-12-01 06:26 UTC, sheenarbw requested changes
There's a little bloat going on.

If we have a big team of devs and every single person were to add random pieces of unused code in all their PRs then our cde base would become very confusig and bloated. It pays to be tidy about things.

Can you please remove the code that doesn't do anything?

2021-12-01 06:26 UTC, sheenarbw commented on frontend/src/components/widgets/BaseButtonLink.js
> +  input: {
Bump.

Do you use `input` anywhere? I can't see it being used. 
We should try not to add extra bloat to the code. If something isn't used then it shouldn't be there.

2021-12-01 06:26 UTC, sheenarbw commented on frontend/src/components/widgets/LinkToUserBoard.js
> +  input: {
Is input being used here?

2021-12-03 06:33 UTC, Vuyisanani approved these changes

2021-12-03 06:36 UTC, Vuyisanani requested changes

2021-12-03 06:36 UTC, Vuyisanani commented on frontend/src/components/regions/UsersAndGroups/Presentation.js
> +            className={classes.input}
Why are you using input class on a TextField?

2021-12-03 06:38 UTC, Vuyisanani commented
You can use the same input, maybe rename the class to a better name for that TextField and use the exact properties

2021-12-07 11:56 UTC, Babalwa01 approved these changes

2021-12-07 20:35 UTC, Vuyisanani approved these changes

2021-12-09 12:36 UTC, sheenarbw approved these changes

2021-12-09 12:36 UTC, merged