Feat/pie chart
Umuzi-org/Tilde pull request #254
Opened 2020-08-11 06:19 UTC by Nhlakanipho12

![Screenshot from 2020-08-06 00-35-19](https://user-images.githubusercontent.com/32615701/89863869-4ca51800-dbab-11ea-90c4-2bf939358eda.png)

2020-08-12 22:23 UTC, Portia-arch commented
@Nhlakanipho12 please fix the conflicts also

2020-09-01 07:03 UTC, Shaheedah commented
Please Review --->
![Screenshot from 2020-09-01 09-02-12](https://user-images.githubusercontent.com/42373959/91812727-e5223b80-ec31-11ea-8788-1cede5d26cd5.png)

2020-09-01 10:48 UTC, XolaniMgube commented
Hey.
I couldn't find the #254 ticket so I could refer to it's description, But this still looks good. Easy understand what's going on. The only thing I find odd is the green colour for the red flag part. That could be because you used react-plotly  and it generates the chart automatically, so isn't there a way you can specify the colours for each label? Unless the colours don't really matter, then its fine because it looks good.

2020-09-02 08:57 UTC, sheenarbw requested changes
This is good.

But I'm seeing some node_module files in your pr. So something weird is happening there.  Rememver that node_modules should never be committed.

Please take a look over your PR yourself and get rid of the extra stuff

2020-09-02 18:37 UTC, Lebogang-cloud reviewed
Good work

Your pie chart can accept values as part of the requirements. It is easy to understand.

2020-09-03 06:27 UTC, Lisa1400 commented
Well done, it looks really good. From my side just make it prettier, the code has open spaces.

2020-09-04 08:19 UTC, Lisa1400 approved these changes

2020-09-07 10:39 UTC, sheenarbw requested changes
There are node_modules and also changes to the main frontend.

Always be careful to only work on code you are meant to work on. Why do you think it would be good to add a pie chart with nonesense data to the main frontend? You know people use that  thing, right? 

Please make sure that no piece of code you are writing here has anything to do with the `frontend` folder. Every change you make should be inside the `experimental-frontend` folder

2020-09-07 10:39 UTC, sheenarbw commented on experimental-frontend/package.json
> +    "react-chartjs-2": "^2.10.0",
What is chartjs for?  Plotly was already installed

2020-09-07 10:39 UTC, sheenarbw commented on frontend/src/components/regions/PieChartDemo/Presentation.js
> +
Please remove this file. 

Remember that you are working on th experimental frontend only. What is this for?

2020-09-07 10:39 UTC, sheenarbw commented on frontend/src/components/regions/PieChartDemo/index.js
> +    return (
Please remove this file. 

Remember that you are working on th experimental frontend only. What is this for?

2020-09-08 17:14 UTC, Shaheedah commented
Hi Sheena I think you reviewed the old code, changes were made on the PR from the 27th of August. Please see these commits:
- 60b92cba6ff75898fab54a089bae48c20aef3c05
- fda38dbb737bd326135b1c90c37c183c4e5f38e1
- f1ebc63362bba16d51ce2b1b809db727f1f917ba
- 88e6cc2a2489b24e24d08f710eb942ba68897edd
- e1dac5cc1e7ab8b4f93175ed6126b9d77eefec12
What we still need to do is remove the node modules on the frontend folder

2020-09-11 07:41 UTC, closed without merging