created leave model
Umuzi-org/Tilde pull request #257
Opened 2020-08-26 13:45 UTC by Tadii3108

2020-08-27 09:16 UTC, Andy-Nkumane requested changes
I had a look at the current leave form and saw that it has `amount of days` - can you confirm if that field is required or not

2020-08-27 09:16 UTC, Andy-Nkumane commented on backend/attendance/models.py
> +    LEAVE_TYPE = (("1", "Annual Leave"),("2", "Sick Leave"),("3", "Family Responsibility"))
How about adding maternity and paternity leaves to the leave type

2020-08-27 10:44 UTC, Tadii3108 commented
> I had a look at the current leave form and saw that it has `amount of days` - can you confirm if that field is required or not

I'm not sure I understand. Required as in if days as a whole are required or specifically the field `amount of days` is required *instead of* another possible way of having the days presented?

2020-08-27 11:04 UTC, Tadii3108 commented on backend/attendance/models.py
> +    LEAVE_TYPE = (("1", "Annual Leave"),("2", "Sick Leave"),("3", "Family Responsibility"))
Wil do.

2020-08-27 11:06 UTC, Tadii3108 commented on backend/attendance/models.py
> +    LEAVE_TYPE = (("1", "Annual Leave"),("2", "Sick Leave"),("3", "Family Responsibility"))
Wait, wouldn't those two - maternity and paternity leaves - fall under Family responsibility?

2020-08-27 16:19 UTC, Andy-Nkumane commented on backend/attendance/models.py
> +    LEAVE_TYPE = (("1", "Annual Leave"),("2", "Sick Leave"),("3", "Family Responsibility"))
Have a look at this https://docs.google.com/forms/d/e/1FAIpQLSdRy444hA3WR4Vul4nTXOuC0x9ZuA3TFBaB8aA-PPMDCeQN8g/viewform

2020-08-27 16:21 UTC, Andy-Nkumane commented
> > I had a look at the current leave form and saw that it has `amount of days` - can you confirm if that field is required or not
> 
> I'm not sure I understand. Required as in if days as a whole are required or specifically the field `amount of days` is required _instead of_ another possible way of having the days presented?

The number of days for leave, excluding weekends and public holidays

2020-09-01 22:01 UTC, Andy-Nkumane requested changes
This is looking good, just a few things.

2020-09-14 05:51 UTC, sheenarbw approved these changes

2020-09-14 05:51 UTC, merged