User detailed stats story assets update
Umuzi-org/Tilde pull request #267
Opened 2021-11-24 18:57 UTC by Babalwa01

Related issues: [#234]

## Description:

What are you up to? Fill us in :)

## Screen
![userdetailedstats](https://user-images.githubusercontent.com/52567054/143297959-25099830-72b5-4e30-bfa2-4c69d88a6099.png)
shots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-24 19:50 UTC, Vuyisanani requested changes

2021-11-24 19:50 UTC, Vuyisanani commented on frontend/src/components/regions/UserDashboard/UserDetailedStats.js
> -          <TableCell>Cards in complete column as assignee</TableCell>
You aren't removing on what you already have, but adding for Status `Blocked`  and  `Ready`

2021-11-25 09:45 UTC, Vuyisanani approved these changes

2021-11-25 09:54 UTC, Vuyisanani approved these changes

2021-11-25 10:06 UTC, kaleem99 approved these changes

2021-12-01 06:17 UTC, sheenarbw requested changes
The column names dont look right to me. Please pull the lastest code on the base branch and check what data actually pulls through.

I did rename things after Eckard worked on stuff in order to make things more consistend.

2021-12-02 19:08 UTC, kaleem99 approved these changes

2021-12-07 18:49 UTC, kaleem99 approved these changes

2021-12-08 11:01 UTC, Vuyisanani approved these changes

2021-12-09 12:23 UTC, sheenarbw approved these changes

2021-12-09 12:23 UTC, merged