Exit popup modal (x)
Umuzi-org/Tilde pull request #276
Opened 2021-12-02 05:05 UTC by Vuyisanani

Related issues: [please specify]

## Description:
When on a mobile device, we could not close the help popup , so we added an exit (x)

What are you up to? Fill us in :)

## Screenshots/videos

<img width="333" alt="Screenshot 2021-12-02 at 07 05 01" src="https://user-images.githubusercontent.com/35369692/144361156-a9729b20-f47d-453c-be5d-641d074c8021.png">

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-02 13:24 UTC, Babalwa01 requested changes
Hey Viro. Looks good. could you please also style the (X) so that it shows that it is clickable. maybe it could be inside a circle and also a pointer when you hover around it? and could you please make it a lowercase x

2021-12-07 16:29 UTC, Babalwa01 requested changes
@Vuyisanani could you please also fix the functionality, when I click on the modal the second time it doesn't open, and shows the following instead:
![modal](https://user-images.githubusercontent.com/52567054/145068009-6beb6bfa-786f-468f-8393-5eff68083c78.png)

2022-01-17 20:21 UTC, Babalwa01 approved these changes

2022-01-19 06:45 UTC, sheenarbw requested changes

2022-01-19 06:45 UTC, sheenarbw commented on frontend/src/components/regions/AddCardReviewModal/index.js
> +    document.getElementById("popUpInfo").remove();
I think we should use React mechanisms here, don't interact directly with the dom.  Are we managing the opening and closing of this modal using state or redux?  Please use the mechanisms in place.

2022-01-26 06:55 UTC, sheenarbw requested changes
Why should only one Modal have an X. Why not all our modals?

2022-01-31 07:16 UTC, Babalwa01 approved these changes

2022-02-01 06:13 UTC, Sbonelo01 requested changes

2022-02-01 06:13 UTC, Sbonelo01 commented on frontend/src/components/regions/AddCardReviewModal/Presentation.js
> +          X
Hi there @Vuyisanani , not make use of the exit icon found in the material UI icons ?

2022-04-21 10:43 UTC, closed without merging