#232 added column cards count to pie chart
Umuzi-org/Tilde pull request #297
Opened 2021-12-13 21:12 UTC by Babalwa01

Related issues: [#232 ]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos
![piechart_cardscount](https://user-images.githubusercontent.com/52567054/145889399-2774d082-3750-4e11-9324-843679407b3f.png)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-14 09:11 UTC, FaithMo approved these changes
Looks good

2021-12-14 11:55 UTC, sheenarbw requested changes

2021-12-14 11:55 UTC, sheenarbw commented on frontend/src/components/regions/UserDashboard/UserDetailedStats.js
> +  const cardsAssignedWithStatusComplete = detailedStats.cardsAssignedWithStatusComplete;
Please make use of destructuring.

2021-12-14 11:55 UTC, sheenarbw commented on frontend/src/components/regions/UserDashboard/UserDetailedStats.js
> +    { name: `Complete (${cardsAssignedWithStatusComplete})`, value: cardsAssignedWithStatusComplete },
Please make sure all the different card statuses are covered. Include Blocked.

2021-12-14 13:04 UTC, Babalwa01 commented
![piechart](https://user-images.githubusercontent.com/52567054/146003557-0d9a6e40-1330-4561-9b03-5a2b2d639aa8.png)

2021-12-15 06:03 UTC, FaithMo approved these changes

2021-12-15 06:34 UTC, Vuyisanani requested changes
Please resolve your merge conflicts first

2021-12-15 11:23 UTC, Sbonelo01 approved these changes

2022-01-11 04:42 UTC, Vuyisanani approved these changes

2022-01-11 08:31 UTC, sheenarbw requested changes
It looks like it works, but the code can be much simpler.  This problem is not a very complicated one, it doesn't need this much spagetti. 

If you have a piece of code that needs some knowledge then try to find the most straightforward way to make that knowledge available.  For me to see how the colours are derived I shouldn't need to go on a treasure hunt.

2022-01-11 08:31 UTC, sheenarbw commented on frontend/src/components/regions/UserDashboard/utils.js
> +export const fillColor = (columnName) => {
This seems a bit overkill. There is a much simpler way. If we just treat data as data then you dont even need a function to work this stuff out.

2022-01-17 20:18 UTC, Vuyisanani approved these changes

2022-01-19 06:35 UTC, sheenarbw approved these changes

2022-01-19 06:36 UTC, merged