fixed broken link
Umuzi-org/Tilde pull request #342
Opened 2022-01-25 09:54 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-25 10:00 UTC, kaleem99 commented
![image](https://user-images.githubusercontent.com/62307224/150954984-dce850f8-07c8-456b-8f02-23819a0397f5.png)

2022-01-25 20:58 UTC, Vuyisanani approved these changes

2022-01-26 06:10 UTC, sheenarbw requested changes
Please fix the story without breaking anything else. It's important not to introduce new bugs.

2022-01-26 06:10 UTC, sheenarbw commented on frontend/src/components/regions/UserDetails/TeamsTable/Presentation.js
> +                    authUser.teamMemberships[team]) && (
Please don't fix the story in such a way as to break the actual frontend. 

We need the story to work AND we need Tilde to not break.

If you look at the redux store in the running application you will see that the authUser object looks lvery different from what you put there.

2022-01-31 12:26 UTC, Sbonelo01 approved these changes

2022-01-31 12:39 UTC, Sbonelo01 requested changes
Wrong PR approved. please dismiss the review and push the necessary changes

2022-02-01 05:29 UTC, Sbonelo01 approved these changes

2022-02-02 12:55 UTC, FaithMo requested changes

2022-02-02 12:55 UTC, FaithMo commented on frontend/src/components/regions/UserDetails/TeamsTable/Presentation.js
> +                  {console.log(authUser)}
Please remove printing statement

2022-02-02 13:08 UTC, FaithMo approved these changes

2022-02-07 11:04 UTC, sheenarbw requested changes
You shouldn't be making changes to TeamsTable/Presentations.js. 

You just need to make the story work. The component already does the right thing. Just the story is broken.

2022-02-07 11:04 UTC, sheenarbw commented on frontend/src/components/regions/UserDetails/TeamsTable/Presentation.js
> +                    authUser.permissions) && (
authUser.permissions.teams[team.id] basically says: Does the authenticated have a permission over the current team.

If the authenticated user does not have permission then they should not see the view button. 

Remember that this code works in production. Just the story is broken. Please dont break production code in order to make the story work. Just fix the story.

2022-02-07 11:04 UTC, sheenarbw commented on frontend/src/stories/TeamsTable.stories.js
> +  authUser: user
What's the difference between  "./fixtures/user.json" and  "./fixtures/authUser.json"?

Please make sure you pass the right object in.

The authUser is the user that is currently authenticated.
The user if the person we are looking at. 

So if Kaleem logs in and looks at Babalwa's info, then the authuser is Kaleem and the the user is Babalwa.

The data structures are different.

2022-02-09 07:27 UTC, Babalwa01 approved these changes
Hey Kaleem. Well done. There are also some other broken stories but they are not mentioned in the ticket maybe there will be other tickets created for them:
- DueTime AgileCard story and `ProjectDetails` story

2022-02-09 14:58 UTC, FaithMo approved these changes

2022-02-10 03:56 UTC, sheenarbw requested changes
Please make sure that this works if you are not looking at your own team memberships. Mostly when making use of this component you would be looking at other people's team memberships.

Please make sure you know the difference between the authenticated user and any other user. 

If I am logged in then I am the authenticated user.
When I am authenticated then I can look at any users team memberships.  I probabaly dont care too much about looking at my own team memberships.  

Please use the right data for the right purpose

2022-02-10 03:56 UTC, sheenarbw commented on frontend/src/stories/TeamsTable.stories.js
> +  teams: authUser.teamMemberships,
The authuser and the user are not necessarily the exact same person. You Kaleem, might be looking at Babalwa's board. That would mean that the authuser is you, Kaleem. And the user is Babalwa.

2022-02-10 03:56 UTC, sheenarbw commented on frontend/src/stories/TeamsTable.stories.js
> -import user from "./fixtures/user.json";
please make use of the user AND the authUser. They have different purposes. Both are relevent

2022-02-15 06:41 UTC, sheenarbw approved these changes

2022-02-15 06:41 UTC, merged