Teams dashboard
Umuzi-org/Tilde pull request #361
Opened 2022-02-06 18:45 UTC by Babalwa01

Related issues: [#300 ]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos
![lineChart](https://user-images.githubusercontent.com/52567054/152696386-3e5f28f2-f86c-4558-b2fd-796b77c1a10a.png)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-06 18:51 UTC, Babalwa01 commented
Please kindly review but not yet officially. The LineCharts only display the correct minimum and maximum dates for the team members whose IDs are not included in the `activityLogDayCounts` object in `src/stories/TeamDashboard.stories.js`

2022-02-09 17:58 UTC, kaleem99 requested changes
- looks good but the date range for the first 3 users is different than the date range for the rest of the users, also looks like the tests can be made drier by removing one of the activityLogDayCounts objects.
- also in the utils.js file the getMinAndMaxDate and getMinimumAndMaximumValue seems to be doing similar things it would be better to use one function for iterating through activityLogDayCounts object and then call the two functions and check for the minMax date and minMax Value.

2022-02-16 06:03 UTC, Babalwa01 commented
I have thus far managed to make the Line charts have the same dates. I am currently stuck on sorting the dates to be in ascending order on the Line Chart
![LineChart](https://user-images.githubusercontent.com/52567054/154205771-2b576c5c-d634-4467-997e-b511f135b5e9.png)

2022-02-16 20:39 UTC, Babalwa01 commented
![lineChart](https://user-images.githubusercontent.com/52567054/154353207-934aa5ef-4157-4b5f-baab-65df128d1ecd.png)

2022-02-17 13:43 UTC, kaleem99 approved these changes

2022-02-17 14:23 UTC, Sbonelo01 approved these changes

2022-02-21 06:30 UTC, Vuyisanani approved these changes

2022-02-21 06:33 UTC, sheenarbw requested changes
This is good. There is just a bit of polish. It would also be good to make sure that there aren't gaps in the data.

2022-02-21 06:33 UTC, sheenarbw commented on frontend/src/components/pages/TeamDashboard/Presentation.js
You are importing 2 things from utils. Wouldn't it make sense to have 1 import statement instead of 2?

2022-02-21 06:33 UTC, sheenarbw commented on frontend/src/components/pages/TeamDashboard/utils.test.js
> +      },
should the 18th be in here too? Just thinking that it might look like folks are reviewing every day when they are not.

2022-02-21 17:50 UTC, Babalwa01 commented
![dateRangeXAxis](https://user-images.githubusercontent.com/52567054/155005524-190cb356-b2a2-4790-a7d8-0f4bb896062c.png)

2022-02-21 20:04 UTC, Sbonelo01 approved these changes

2022-02-22 18:44 UTC, kaleem99 approved these changes

2022-02-23 06:28 UTC, sheenarbw approved these changes

2022-02-23 06:28 UTC, merged