#347 put getAgeString tests in the correct file
Umuzi-org/Tilde pull request #363
Opened 2022-02-08 07:11 UTC by Babalwa01

Related issues: [#347 ]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-08 12:22 UTC, FaithMo approved these changes

2022-02-09 18:30 UTC, Sbonelo01 approved these changes

2022-02-10 04:03 UTC, sheenarbw requested changes
better. But there is still more to be cleaned up

2022-02-10 04:03 UTC, sheenarbw commented on frontend/src/components/widgets/utils.test.js
> +  const card = {
While we are at it, let's lclean these tests up the rest of the way. `getAgeString` doesn't need to know about cards. It doesn't need to know anything except a time.

This is much cleaner:
```
date = date.setDate(today.getDate() - 31)
expect(getAgeString(date)).toBe("1 month ago");
```

2022-02-15 06:57 UTC, FaithMo approved these changes

2022-02-15 07:18 UTC, Sbonelo01 approved these changes

2022-02-16 06:03 UTC, sheenarbw approved these changes

2022-02-16 06:03 UTC, merged