Whitespace under view button/371
Umuzi-org/Tilde pull request #378
Opened 2022-02-23 05:54 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-23 07:19 UTC, Babalwa01 approved these changes

2022-02-24 11:44 UTC, kaleem99 approved these changes

2022-02-28 06:33 UTC, sheenarbw requested changes
Please always remember to add a screenshot of changes to they gui. 

Usually we use useStyles for styling... is there a reason to adopt a new standard for this problem?

2022-02-28 06:33 UTC, sheenarbw commented on frontend/src/components/regions/UsersAndGroups/Presentation.js
> +        <div>&nbsp;</div>
Have you considered using styling? We usually handle spacing inside useStyles. 
Why would we do this one differently?

2022-03-02 20:36 UTC, Babalwa01 approved these changes

2022-03-03 19:21 UTC, kaleem99 approved these changes

2022-03-04 00:50 UTC, sheenarbw approved these changes

2022-03-04 00:50 UTC, merged