Move users and groups to pages/397
Umuzi-org/Tilde pull request #407
Opened 2022-03-10 13:54 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-11 00:44 UTC, Babalwa01 requested changes
Hey Faith. When users is clicked on the nav it generates an error:
![UsersAndGroups](https://user-images.githubusercontent.com/52567054/157779842-c4b9d131-648b-4614-90f3-851ce90ae19a.png)

2022-03-15 14:20 UTC, kaleem99 approved these changes

2022-03-16 12:51 UTC, kaleem99 requested changes
- Hi Faith looks good but storybook is showing errors pls make sure to update the imports in storybook e.g 
- import UsersAndGroups from "../components/pages/UsersAndGroups/Presentation.jsx";

2022-03-17 05:10 UTC, Babalwa01 approved these changes

2022-03-17 05:28 UTC, Babalwa01 requested changes

2022-03-17 05:28 UTC, Babalwa01 commented on frontend/src/components/pages/UsersAndGroups/utils.js
> +export function getPrStatus (oldestOpenPrTime) {
Hey Faith please apply destructing here also for the functions' parameters

2022-03-17 16:05 UTC, FaithMo commented on frontend/src/components/pages/UsersAndGroups/utils.js
> +export function getPrStatus (oldestOpenPrTime) {
Hi Babalwa. I don't think I need to destructure this. This is the utils.js file

2022-03-17 19:47 UTC, Babalwa01 approved these changes

2022-03-22 06:18 UTC, kaleem99 approved these changes

2022-03-28 04:16 UTC, sheenarbw approved these changes

2022-03-28 04:17 UTC, merged