teamDashboard formatted code to match Style_guide.md #399
Umuzi-org/Tilde pull request #413
Opened 2022-03-16 07:43 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-17 05:03 UTC, Babalwa01 approved these changes

2022-03-22 06:20 UTC, KhalidUmuzi requested changes
Also remember to change the file name extensions to .jsx

2022-03-22 12:50 UTC, FaithMo approved these changes

2022-03-24 06:20 UTC, KhalidUmuzi approved these changes

2022-03-28 03:31 UTC, sheenarbw approved these changes

2022-03-28 03:31 UTC, merged