Super user should be able to set due date
Umuzi-org/Tilde pull request #462
Opened 2022-04-21 07:43 UTC by Sbonelo01

Related issues: [458]

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-22 14:12 UTC, FaithMo approved these changes, later dismissed

2022-04-25 05:56 UTC, kaleem99 approved these changes, later dismissed

2022-04-26 13:12 UTC, sheenarbw requested changes
There seem to be misunderstandings in here. 

Don't guess at data structures, rather look at the actual data to see what shape things have.

2022-04-26 13:12 UTC, sheenarbw commented on frontend/src/components/regions/CardDetails/CardDetails.test.js
> +test(`canSetDueTime function returns true if card doesn't belongs to current user,
This is complicated.

How about `canSetDueTime function returns true for superusers`

2022-04-26 13:12 UTC, sheenarbw commented on frontend/src/components/regions/CardDetails/CardDetails.test.js
> +          isSuperuser: true,
This data structure doesn't match the structure we use on Tilde. And most of the data is not relevant to the test. 
Either a person is a superuser or they aren't. A person doesn't get superuser permission over a single team.

Please open Tilde in your browser. Open the redux dev tools (chrome) and look at the state. Look inside `state.App.authUser`.

Please use a data structure that matches that. 

also for this test: `authUser.permissions = {}`.  No individual permissions are necessary if a person has superuser status.

2022-05-05 12:35 UTC, FaithMo approved these changes

2022-05-11 18:51 UTC, Vuyisanani approved these changes

2022-05-16 14:47 UTC, sheenarbw approved these changes

2022-05-16 14:47 UTC, merged