Status modal fix
Umuzi-org/Tilde pull request #481
Opened 2022-05-05 20:44 UTC by Sbonelo01

Related issues: [#470 ]

## Description: https://github.com/Umuzi-org/Tilde/projects/2#card-80933190

**Before:**
![Screenshot_2022-05-05_21-53-36(fix-modal-before)](https://user-images.githubusercontent.com/37469171/167022333-773816d6-5a15-4a77-9090-9446ecfbd4de.png)

**After:**
![Screenshot_2022-05-05_22-37-49(fix-modal-after)](https://user-images.githubusercontent.com/37469171/167022423-43f695a2-dc2a-4234-9a15-2206c85c6b10.png)

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-09 05:37 UTC, FaithMo approved these changes

2022-05-11 19:06 UTC, Vuyisanani requested changes
Can you consider this comment on the ticket:

`Clicking that button opens up something like a modal but it's weirdly off to the side and works badly on mobile devices.`

Please make sure you also add mobile device screenshot, currently not looking great on all devices.

2022-05-11 20:37 UTC, Sbonelo01 commented
> Can you consider this comment on the ticket:
> 
> `Clicking that button opens up something like a modal but it's weirdly off to the side and works badly on mobile devices.`
> 
> Please make sure you also add mobile device screenshot, currently not looking great on all devices.

Thanks @Vuyisanani for the review, I have added a screenshot for Mobile. Please let me know what should change.

2022-05-12 16:01 UTC, Vuyisanani approved these changes

2022-05-17 09:22 UTC, sheenarbw approved these changes

2022-05-17 09:22 UTC, merged