Feat/expand review merge develop
Umuzi-org/Tilde pull request #483
Opened 2022-05-10 20:23 UTC by Sbonelo01

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

```
git checkout develop 
git pull
git checkout feat/expand-review 
git pull 
git merge develop
```
and moved files from `CardDetails` to `Pages`
- [x] I have merged develop into my current branch

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-12 13:29 UTC, FaithMo approved these changes
merge conflicts resolved

2022-05-12 16:13 UTC, Vuyisanani approved these changes

2022-05-17 09:15 UTC, sheenarbw requested changes
There is a bug. The bug is due to wheel-reinvention. 

Please look into the onClose parameter.

2022-05-17 09:15 UTC, sheenarbw commented on frontend/src/components/pages/CardDetails/Review.jsx
> +          setOpenReviewPopUp(false);
If I try to select some text from the popup so I can copy-paste it then the popup randomly closes. 

Please remove this div and this event handler.

Rather make use of the onClose event. 

Closing a modal is a perfectly normal thing to do. When something feels perfectly normal then see how it's already done, you dont need to reinvent this wheel. Rather stick to conventions.

2022-05-20 20:05 UTC, FaithMo approved these changes

2022-05-25 03:52 UTC, Vuyisanani approved these changes

2022-05-31 09:52 UTC, merged