Fix failing unit test
Umuzi-org/Tilde pull request #485
Opened 2022-05-11 17:29 UTC by KhalidUmuzi

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-05-13 13:20 UTC, FaithMo approved these changes
looks good

2022-05-13 13:50 UTC, Sbonelo01 approved these changes

2022-05-16 14:35 UTC, sheenarbw requested changes
This works but the code has some strangeness to it.  

If we introduce a new convention to the code then it's good to know that the juniors will follow that convention. The main thing here is that we should aim to use restructuring and avoid using positional arguments. And when in doubt be consistent. 

The name is a bit of a bunny one - if I just see how the function is used then it is not at all clear how the date is used in the filter, is it a start date or an end date? If I want to understand a function call then I need to go sniff around in the function definition. Ideally if I look at a line of code I should understand it's intention without going on any treasure hunts. 

If I put this code in I would probably end up cleaning it up myself because making another issue on the board would be as much effort.

2022-05-16 14:35 UTC, sheenarbw commented on frontend/src/components/pages/TeamDashboard/Presentation.jsx
> +  const dateFilter = new Date();
If I ask you to explain to me in English what the date filter is, you will say it is the "end date" or the "current date". It's used for filtering, but what is it? It's definitely not a filter. A filter is a function.

2022-05-16 14:35 UTC, sheenarbw commented on frontend/src/components/pages/TeamDashboard/utils.js
> +export function updateActivityLogDayCounts({ activityLogDayCounts }, dateFilter) {
Why use positional arguments? Isn't destructuring generally much safer? And it's good to be consistent. 

`export function updateActivityLogDayCounts({ activityLogDayCounts, dateFilter }) `

2022-05-19 09:19 UTC, Sbonelo01 approved these changes

2022-05-20 19:59 UTC, FaithMo approved these changes

2022-05-24 06:00 UTC, sheenarbw approved these changes

2022-05-24 06:00 UTC, merged