added pr procedure doc
Umuzi-org/Tilde pull request #494
Opened 2022-05-29 23:49 UTC by KhalidUmuzi

Related issues: [please specify]

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [X] I have merged the develop branch into my branch and fixed any merge conflicts
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-05-30 07:12 UTC, Sbonelo01 requested changes
Slight grammar mistakes ...

2022-05-30 07:12 UTC, Sbonelo01 commented on pull_request_procedure.md
> +For this, we will be using the github conversation as a way to provide feedback as well as show that a person has addressed the feedback. On an existing Pull Request, you will be receiving feedback o
Here, I think you meant:

"PRs that don’t have all conversations resolved will be pushed back into the review feedback column" ?

2022-05-30 07:12 UTC, Sbonelo01 commented on pull_request_procedure.md
> +If you have addressed the feedback in the form of a chat outside of github, please mention it regardless. Eg “Khalid has made a change and Sheena has provided feedback on why this piece of code is he
Maybe change "They have a conversation offline ..." to "They had a conversation offline ..." Also, I am not sure if the last sentence should still be inside inverted commas.

2022-05-30 07:12 UTC, Sbonelo01 commented on pull_request_procedure.md
> +The second thing to make sure of is that all previous feedback needs to be addressed in this PR. There may be a long conversation that took place on the same PR and you need to be aware of this chang
Maybe these two points can be bullets?

2022-06-05 21:06 UTC, Sbonelo01 approved these changes

2022-06-07 08:16 UTC, TheAbstract approved these changes

2022-06-07 12:02 UTC, sheenarbw approved these changes

2022-06-07 12:02 UTC, merged