"view content" button visible on all cards in the backlog
Umuzi-org/Tilde pull request #530
Opened 2022-06-22 19:06 UTC by Sbonelo01

Related issues: [#467 ]

## Description:
The view content button is visible on all cards in the backlog, without adding any duplicates

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-24 06:16 UTC, FaithMo approved these changes

2022-06-28 17:51 UTC, Vuyisanani approved these changes

2022-06-29 06:24 UTC, sheenarbw requested changes
This puts the bug back.

See here: https://github.com/Umuzi-org/Tilde/issues/467#issuecomment-1165444418

2022-06-29 12:00 UTC, Sbonelo01 commented
> This puts the bug back.
> 
> See here: [#467 (comment)](https://github.com/Umuzi-org/Tilde/issues/467#issuecomment-1165444418)

Thanks, please see this reply: https://github.com/Umuzi-org/Tilde/issues/467#issuecomment-1165481009

I have produced screenshots of how different cards look on my end. Can you please let me know which type of card produces the bug on your side

2022-07-08 14:45 UTC, sheenarbw approved these changes

2022-07-08 14:45 UTC, merged