Widget for buttons
Umuzi-org/Tilde pull request #548
Opened 2022-07-15 01:58 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-19 15:51 UTC, Sbonelo01 requested changes
This button looks good.

The second step of this issue says that we now need to :
```
"Make sure we always import this new widget and use it instead of using the normal mui button."
```

Can you please also implement this aswell

I'm not sure if this should be in an unprotected branch since we will have to get feedback from dpd first.

2022-07-19 15:51 UTC, Sbonelo01 commented on frontend/src/components/widgets/Button.jsx
> +    border: "1px solid grey",
Can you also please style the button to not always turn its children to upper case.

2022-08-02 10:00 UTC, Sbonelo01 approved these changes

2022-08-16 17:53 UTC, Vuyisanani approved these changes

2022-08-19 06:38 UTC, sheenarbw approved these changes

2022-08-19 06:38 UTC, merged