Finished task
Umuzi-org/Tilde pull request #552
Opened 2022-07-19 23:28 UTC by KhalidUmuzi

Related issues: [please specify]

## Description:

Made sure that all the UserActions components followed the style guide

## Screenshots/videos

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [X] I have merged the develop branch into my branch and fixed any merge conflicts
- [X] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-07-21 05:05 UTC, Ngoakor12 requested changes

2022-07-21 05:05 UTC, Ngoakor12 commented on frontend/src/components/pages/UserActions/Presentation.jsx
> +export default ({
I think this needs a name and needs to be defined with `function` keyword

2022-07-21 05:05 UTC, Ngoakor12 commented on frontend/src/components/pages/UserActions/index.jsx
> +const mapStateToProps = (state) => {
`function` keyword?

2022-07-21 05:05 UTC, Ngoakor12 commented on frontend/src/components/pages/UserActions/Presentation.jsx
> +import { Typography, Paper, Grid } from "@material-ui/core";
- There's [a PR in the works](https://github.com/Umuzi-org/Tilde/issues/472) about importing mui components using paths, I don't this might need to be updated? Unless it doesn't matter since it's not merged yet

- Same thing for the `GithubActivity.jsx` file

2022-08-01 03:46 UTC, Ngoakor12 approved these changes

2022-08-10 18:59 UTC, TheMaja approved these changes

2022-11-24 07:19 UTC, Ngoakor12 commented
Will be addressed by #613

2022-11-24 07:19 UTC, closed without merging