Card to review column with disapproved trusted review/508
Umuzi-org/Tilde pull request #554
Opened 2022-07-21 12:03 UTC by Andy-Nkumane

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-26 12:41 UTC, Samantha-Hampton requested changes
Mostly looks good, see comment about removing test part already done else where

2022-07-26 12:41 UTC, Samantha-Hampton commented on backend/curriculum_tracking/tests/test_AgileCard.py
> +        self.assertEqual(card_assignees, project_assignees)
This all mostly seems to be covered already in this other test class:

```
class start_project_Tests(TestCase):
    def setUp(self):
        bot = SocialProfileFactory(github_name=GIT_REAL_BOT_USERNAME)
        GithubOAuthTokenFactory(user=bot.user)

    def assert_users_same(self, card, project):
        card_assignees = sorted([o.id for o in card.assignees.all()])
        card_reviewers = sorted([o.id for o in card.reviewers.all()])
        project_reviewers = sorted([o.id for o in project.reviewer_users.all()])
        project_assignees = sorted([o.id for o in project.recruit_users.all()])

        self.assertEqual(card_assignees, project_assignees)
        self.assertEqual(card_reviewers, project_reviewers)

    @mock.patch("git_real.helpers.get_repo")
    @mock.patch.object(RecruitProject, "setup_repository")
    def test_start_project_creates_project_if_not_exists(self, get_repo, *_):

        card = factories.AgileCardFactory(
            status=AgileCard.READY,
            recruit_project=None,
            content_item=factories.ProjectContentItemFactory(
                project_submission_type=ContentItem.REPOSITORY
            ),
            assignees=[SocialProfileFactory().user],
        )

        self.assertIsNone(card.recruit_project)

        get_repo.return_value = {
            "full_name": "me/kiff",
            "owner": {"login": "me"},
            "ssh_url": "https://whatever.git",
            "private": True,
            "created_at": timezone.now().strftime(GITHUB_DATETIME_FORMAT),
            "archived": False,
        }

        card.start_project()

        self.assertIsNotNone(card.recruit_project)
        project = card.recruit_project

        card.refresh_from_db()
        project.refresh_from_db()

        self.assert_users_same(card=card, project=project)
        self.assertEqual(project.content_item, card.content_item)
        self.assertTrue(project.setup_repository.called)
        self.assertEqual(card.status, AgileCard.IN_PROGRESS)
        self.assertIsNotNone(project.start_time)
```

So maybe in your setUp you can already start the project and put it in review, which could make the rest of the tests a bit cleaner?

2022-07-28 08:03 UTC, Samantha-Hampton approved these changes
I'm having an issue with running Tilde locally on my machine, so I couldn't run the tests, but looks good to me

2022-08-02 14:36 UTC, Rokhuda approved these changes

2022-08-16 14:59 UTC, sheenarbw requested changes
There is a test script named `curriculum_tracking/tests/test_project_cards_move_when_they_should.py`

Are these tests DRY? Or do they repeat what is in that file?

If these tests do add value, please move them to the other file. 
If these tests add no value then please remove them. 

Sam reported the bug, it would be good to see if she is happy that the bug doesn't exist

2023-08-14 09:59 UTC, closed without merging