Hide deactivated learner from showing in active team
Umuzi-org/Tilde pull request #560
Opened 2022-07-26 23:31 UTC by Sbonelo01

Related issues: [#538 ]

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [  ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-27 20:18 UTC, TheMaja approved these changes

2022-08-01 04:06 UTC, Ngoakor12 requested changes
Seems to be working, but tests fail... I think you forgot to export the function.
![image](https://user-images.githubusercontent.com/54069197/182070163-b86df125-09d4-400e-8f6d-d01875c25d11.png)

2022-08-01 06:26 UTC, Sbonelo01 commented
> Seems to be working, but tests fail... I think you forgot to export the function. ![image](https://user-images.githubusercontent.com/54069197/182070163-b86df125-09d4-400e-8f6d-d01875c25d11.png)

Thanks, yes, I actually hadn't exported it. sorted :)

2022-08-01 06:56 UTC, Ngoakor12 approved these changes

2022-08-10 15:00 UTC, Vuyisanani approved these changes

2022-08-19 08:28 UTC, sheenarbw approved these changes

2022-08-19 08:28 UTC, merged