Removed, renamed and refactored
Umuzi-org/Tilde pull request #569
Opened 2022-08-01 21:50 UTC by KhalidUmuzi

Related issues: [please specify]

## Description:

Agile Card and all subfolders now match the style guide

## Screenshots/videos

## I solemnly swear that:

- [X] My code follows the style guidelines of this project
- [X] I have merged the develop branch into my branch and fixed any merge conflicts
- [X] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-08-02 16:33 UTC, TheMaja approved these changes

2022-11-25 12:12 UTC, FaithMo approved these changes

2022-12-02 10:02 UTC, Vuyisanani requested changes
All looking great, just please fix your merge conflicts

2022-12-07 09:14 UTC, FaithMo approved these changes

2023-01-04 13:56 UTC, sheenarbw approved these changes

2023-01-04 13:57 UTC, merged