initial commit
Umuzi-org/Tilde pull request #585
Opened 2022-08-24 10:25 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-25 04:13 UTC, Ngoakor12 approved these changes

2022-08-25 18:00 UTC, Vuyisanani approved these changes

2022-08-26 09:02 UTC, sheenarbw requested changes
Please don't remove functionality.

2022-08-26 09:02 UTC, sheenarbw commented on frontend/src/apiAccess/apis.js
> +async function activityLogDayCountsPage({ eventTypeName, actorUser, page }) {
what about the effected user? If I receive a review then I would want to know about it. Can you please put the filter back.

Can you also please add the rest of the filters? Here is a list from the backend:

```
filterset_fields = [
        "event_type",
        "actor_user",
        "effected_user",
        "object_1_content_type",
        "object_1_id",
        "object_2_content_type",
        "object_2_id",
    ]
```

2022-09-07 06:00 UTC, closed without merging