Render tidy: region/Agileboard
Umuzi-org/Tilde pull request #588
Opened 2022-08-25 12:47 UTC by Ngoakor12

Related issues: [[https://www.notion.so/regions-AgileBoard-index-js-6985545dd9014b40bc8715d74e45f427](https://www.notion.so/regions-AgileBoard-index-js-6985545dd9014b40bc8715d74e45f427)]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-30 14:28 UTC, Sbonelo01 requested changes
Well done! 

The review here remains the same as this review: 
https://github.com/Umuzi-org/Tilde/pull/589#pullrequestreview-1090377790

2022-09-01 06:23 UTC, Sbonelo01 approved these changes

2022-09-02 15:12 UTC, Vuyisanani approved these changes

2022-09-03 08:36 UTC, sheenarbw approved these changes
very good

2022-09-03 08:36 UTC, merged