tidy renders: region/UserActions
Umuzi-org/Tilde pull request #589
Opened 2022-08-25 13:38 UTC by Ngoakor12

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-30 13:58 UTC, Sbonelo01 requested changes
Well done! the component renders at max 3 times now as opposed to the previous 4.

Please fix the file namings to match our react style guide found here: https://github.com/Umuzi-org/Tilde/blob/develop/frontend/STYLE_GUIDE.md

Please also fix the warnings found on this branch when the app compiles:
```
Compiled with warnings.

./src/components/widgets/ActionLogCards.js
  Line 38:5:  Unnecessarily computed property ["@media (max-width:620px)"] found  no-useless-computed-key
  Line 44:5:  Unnecessarily computed property ["@media (max-width:620px)"] found  no-useless-computed-key

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

```

2022-08-31 09:57 UTC, Ngoakor12 commented
@Sbonelo01 the warnings were already there, but I was able to resolve it

2022-08-31 14:19 UTC, Sbonelo01 approved these changes

2022-09-02 15:14 UTC, Vuyisanani approved these changes

2022-09-03 08:31 UTC, sheenarbw approved these changes

2022-09-03 08:32 UTC, merged