re-renders dont seem to happen here
Umuzi-org/Tilde pull request #594
Opened 2022-08-28 18:53 UTC by Sbonelo01

Related issues: [RENDER tidy]

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-01 06:53 UTC, TheMaja approved these changes

2022-09-01 18:08 UTC, Vuyisanani approved these changes

2022-09-03 07:26 UTC, sheenarbw requested changes
What should happen if the card is undefined? This code is now more brittle than it was before.  Should this PR just be closed? It doesn't seem to do much

2022-09-06 12:48 UTC, Sbonelo01 commented
Closed PR. There are no re-renders happening

2022-09-06 12:48 UTC, closed without merging