reduce re-render on userDashboard
Umuzi-org/Tilde pull request #596
Opened 2022-08-29 14:47 UTC by Sbonelo01

Related issues: [RENDER tidy]

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-01 06:56 UTC, TheMaja approved these changes

2022-09-02 15:19 UTC, Vuyisanani approved these changes

2022-09-03 07:24 UTC, sheenarbw requested changes
When in doubt: don't guess.

Here is the correct mapStateToProps:

```

const mapStateToProps = (state) => {
  return {
    users: state.apiEntities.users,
    userDetailedStats: state.apiEntities.userDetailedStats,
    userBurndownStats: state.apiEntities.burndownSnapshots,
    authUser: state.App.authUser
  };
};
```

Dear reviewers: please make sure that the code you are reviewing actually does what it is meant to do. It's very important.  This PR doesn't address the issue it's meant to address at all.

2022-09-09 11:54 UTC, KhalidUmuzi requested changes
Please make the requested changes as Sheena mentioned. This is still not correct if i look at the whole file.

lines 48-56 are still the same at the moment

2022-09-14 05:15 UTC, KhalidUmuzi requested changes
Please fix Merge conflicts

2022-09-22 01:08 UTC, KhalidUmuzi requested changes

2022-09-22 01:08 UTC, KhalidUmuzi commented on frontend/src/components/pages/UserDashboard/index.jsx
>      // authedUserId: state.App.authUser.userId,
Something wierd is going on here. I don't think the burndown stats is on the dashboard any longer. Its been moved to UserActions That change has been merged into develop already.

We don't want to add it back. I think this file might have been changed when you were looking at something

2022-09-30 12:46 UTC, KhalidUmuzi approved these changes

2022-10-04 04:37 UTC, sheenarbw requested changes
I'm not sure why Khalid's comment wasn't addressed.

2022-10-04 04:37 UTC, sheenarbw commented on frontend/src/components/pages/UserDashboard/index.jsx
> +    userBurndownStats: state.apiEntities.burndownSnapshots,
Why is userBurnDownStats here?  Wasn't it removed on purpose?

If you search for userBurnDownStats in this file then you will see that it is not being used.

2022-10-04 04:37 UTC, sheenarbw commented on frontend/src/components/pages/UserDashboard/index.jsx
> +    fetchUserBurndownStats: ({ userId }) => {
Please also remove this function. It looks like it isn't being used either.

2022-10-07 00:13 UTC, KhalidUmuzi approved these changes

2022-10-11 09:59 UTC, sheenarbw approved these changes

2022-10-11 09:59 UTC, merged