updated files to match style guide, No re-renders
Umuzi-org/Tilde pull request #597
Opened 2022-08-29 15:40 UTC by Sbonelo01

Related issue[RENDER tidy]

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-01 07:15 UTC, TheMaja approved these changes

2022-09-02 15:18 UTC, Vuyisanani requested changes

2022-09-02 15:18 UTC, Vuyisanani commented on frontend/src/components/pages/Login/index.jsx
> +import {useTraceUpdate} from "../../../hooks"
For consistency also add `;` at the end of the line

2022-09-02 15:18 UTC, Vuyisanani commented on frontend/src/components/pages/Login/index.jsx
> +  console.log("xxxxxxx")
Do you need this for? please remove

2022-09-02 15:18 UTC, Vuyisanani commented on frontend/src/components/pages/Login/index.jsx
> +    console.log("e", e)
Please remove

2022-09-13 13:52 UTC, KhalidUmuzi approved these changes

2022-09-13 14:13 UTC, sheenarbw approved these changes

2022-09-13 14:13 UTC, merged