no re-renders found
Umuzi-org/Tilde pull request #600
Opened 2022-08-30 13:03 UTC by Sbonelo01

Related issues: [RENDER tidy]

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-01 07:17 UTC, TheMaja approved these changes

2022-09-02 15:19 UTC, Vuyisanani approved these changes

2022-09-03 07:19 UTC, sheenarbw requested changes
You didn't address the problem. You just changed how some functions are called:

This is the problem: 
```
const mapStateToProps = (state) => {
  return {
    repositories:
      state.apiEntities.repositories === undefined
        ? {}   //  HERE
        : state.apiEntities.repositories,
    commits:
      state.apiEntities.repoCommits === undefined
        ? {} //  HERE
        : state.apiEntities.repoCommits,
    pullRequests:
      state.apiEntities.pullRequests === undefined
        ? {} //  HERE
        : state.apiEntities.pullRequests,
  };
};
```

It should look like:

```
const mapStateToProps = (state) => {
  return {
    repositories: state.apiEntities.repositories,
    commits: state.apiEntities.repoCommits,
    pullRequests: state.apiEntities.pullRequests
  };
};
```

When in doubt: Don't guess.  I also don't think the reviewers actually checked that your code did what it was supposed to do which is a real pity.

2022-09-09 11:56 UTC, KhalidUmuzi requested changes
Please make the requested changes. This still doesnt solve the issue currently the way it is

2022-09-22 01:03 UTC, KhalidUmuzi approved these changes

2022-09-22 07:25 UTC, sheenarbw approved these changes

2022-09-22 07:26 UTC, merged