Render tidy: region/AddCardReviewModal
Umuzi-org/Tilde pull request #601
Opened 2022-08-31 12:13 UTC by Ngoakor12

Related issues: [[https://www.notion.so/regions-AddCardReviewModal-index-js-5c6d711153c844ecbd5f4ada124f4203](https://www.notion.so/regions-AddCardReviewModal-index-js-5c6d711153c844ecbd5f4ada124f4203)]

## Description:

No rerenders were detected. I just updated the component and it's files to match the current styleguide

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-08 09:03 UTC, FaithMo requested changes
I like that you moved StatusHelp to a file of its own

2022-09-08 09:03 UTC, FaithMo commented on frontend/src/components/regions/AddCardReviewModal/StatusHelp.jsx
> +              All the relevent code is in the master branch - The master branch
please also fix this spelling here for "relevant"

2022-09-08 09:45 UTC, FaithMo approved these changes

2022-09-08 12:01 UTC, KhalidUmuzi approved these changes

2022-09-10 09:29 UTC, sheenarbw requested changes
I'm getting this warning:

```
index.js:1 Warning: Failed prop type: The prop `xs` of `Grid` must be used on `item`.
    in WithStyles(ForwardRef(Grid)) (at Presentation.jsx:58)
    in Presentation (at AddCardReviewModal/index.jsx:53)
    in AddReviewModalUnconnected (created by ConnectFunction)
    in ConnectFunction (at Presentation.js:155)
    in div (at Presentation.js:153)
    in Presentation (at AppHeaderAndMenu/index.js:41)
    in AppMenuUnconnected (created by ConnectFunction)
    in ConnectFunction (at App/index.js:79)
    in Routes (at App/index.js:67)
    in ThemeProvider (at App/index.js:66)
    in AppUnconnected (created by ConnectFunction)
    in ConnectFunction (at src/index.js:15)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:14)
    in Provider (at src/index.js:13)
```

Besides that it all looks good

2022-09-14 15:01 UTC, FaithMo reviewed
I did not experience the error,

2022-09-14 15:08 UTC, Ngoakor12 commented
> I did not experience the error,

I fixed it. A new warning popped up whenever you clicked the "add review" button on a card.

2022-09-15 05:56 UTC, FaithMo approved these changes

2022-09-16 11:57 UTC, KhalidUmuzi approved these changes

2022-09-20 05:31 UTC, sheenarbw approved these changes

2022-09-20 05:31 UTC, merged