Use UserAvatarLink widget
Umuzi-org/Tilde pull request #610
Opened 2022-09-07 15:29 UTC by Ngoakor12

Related issues: [[Use UserAvatarLink widget](https://www.notion.so/2-Make-use-of-the-UserAvatarLink-widget-in-the-card-details-page-56bde45f045044fea3cd1e0f7e1d0554)]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos
![image](https://user-images.githubusercontent.com/54069197/188917749-65f99d5b-3853-4e05-8c30-40029db0fb6d.png)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-08 10:02 UTC, FaithMo approved these changes

2022-09-16 11:49 UTC, KhalidUmuzi approved these changes

2022-09-20 05:41 UTC, sheenarbw requested changes
One bug.

2022-09-20 05:41 UTC, sheenarbw commented on frontend/src/components/widgets/AssigneesList.jsx
> +          <TableRow key={userIds}>
userIds should be an array of Ids, not just one id.  That is why it is called `userIds` and not `userId`

eg input would be:

```
{
userNames: ["you@umuzi.org", "me@umuzi.org"],
userIds:        [3,                            2],
}
````

Rather:

```
userNames.map((name,index)=>{
    const userId = userIds[index];
   return (<TableRow key={userId}> ..... </TableRow>)
})
```

2022-09-21 07:48 UTC, FaithMo approved these changes

2022-09-21 09:52 UTC, KhalidUmuzi approved these changes

2022-09-22 07:39 UTC, sheenarbw approved these changes

2022-09-22 07:39 UTC, merged