Update various api serializers to expose total number a card moves to review feedback
Umuzi-org/Tilde pull request #622
Opened 2022-09-27 11:37 UTC by Andy-Nkumane

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-07 10:15 UTC, sheenarbw requested changes
The logic is incorrect. Also it is not DRY. 

Please test your work.  I also think you'll need to update the existing tests so that they pass. The api test mixin will end up failing a bunch of stuff if you add extra fields that retuyrn falsy data by default.  If that sentence doesn't make sense, please run the tests

2022-10-07 10:15 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            "total_number_of_negative_reviews",
maybe a better name would be:

number_of_times_card_moved_to_review_feedback.

If this was really the total number of negative reviews then the call would be very different.

2022-10-07 10:15 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            LogEntry.objects.filter(effected_user=instance.assignees.first(),
This query gets the total number of times any card belonging to the user was bounced back.

You need to filter by the actual card we are looking at. 

If I have 2 cards:

card_1 bounced 2 times and card_2 bounced 3 times then the total bounces for card_1 is 2 and not 5.

2022-10-07 10:15 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            LogEntry.objects.filter(effected_user=instance.assignees.first(),
please write a test

2022-10-07 10:15 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            LogEntry.objects.filter(effected_user=instance.recruit_users.first(),
not DRY.  This function has the same problem as the others

2022-10-26 10:06 UTC, Samantha-Hampton requested changes
I think it mostly looks ok, but maybe good to write that extra test Sheena was suggesting that checks that the correct values are coming out, eg:

If I have 2 cards:

card_1 bounced 2 times and card_2 bounced 3 times then the total bounces for card_1 is 2 and not 5.

2022-10-26 10:06 UTC, Samantha-Hampton commented on backend/curriculum_tracking/serializers.py
> +        if instance.recruit_project:
maybe we aren't interested in topics for this but there are some topics that require review, so then if they did get a negative review, it wouldn't come up here. Maybe we just need to check to make sure we aren't filtering out data we may want?

2022-11-23 10:17 UTC, Samantha-Hampton requested changes

2022-11-23 10:17 UTC, Samantha-Hampton commented on backend/curriculum_tracking/tests/test_api_views.py
> +        c.timestamp = c.timestamp - timedelta(days=2)
I'm getting an error when I run the tests:

```
ERROR: test_get_number_of_times_card_moved_to_review_feedback (curriculum_tracking.tests.test_api_views.AgileCardViewsetTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sam/Documents/Umuzi/Products/Tilde/backend/curriculum_tracking/tests/test_api_views.py", line 500, in test_get_number_of_times_card_moved_to_review_feedback
    c = LogEntry.objects.filter(
AttributeError: 'NoneType' object has no attribute 'timestamp'

----------------------------------------------------------------------
Ran 70 tests in 116.148s

FAILED (errors=1)
```

So it's not registering a matching log entry object, so there is no timestamp to update

2022-11-30 13:27 UTC, Samantha-Hampton requested changes

2022-11-30 13:27 UTC, Samantha-Hampton commented on backend/curriculum_tracking/tests/test_api_views.py
> +        recruit = UserFactory()
extremely minor, but this recruit item does not appear to be used, so can be deleted

2022-12-06 09:52 UTC, Rokhuda approved these changes

2022-12-08 07:32 UTC, sheenarbw requested changes
A few things can be made more efficient. And the code is still not DRY

2022-12-08 07:32 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +    def get_number_of_times_card_moved_to_review_feedback(self, instance):
This really doesn't look DRY to me. Please avoid copy-pasting whole functions.

2022-12-08 07:32 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +                object_1_id=instance.recruit_project.pk,
This query should be more explicit. 

We can have a recruit project with the same id as a repo. We can have a recruit project with the same id as a review as well.

Please also add object_1's content type to the query. Explicit is better than implicit.

2022-12-08 07:32 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            LogEntry.objects.filter(effected_user=instance.recruit_users.first(),
please avoid copy paste. DRY code is better.

You can add a function to the RecruitProject model. Then just call the function as needed.

There is no reason to introduce this technical debt now.

2022-12-08 07:32 UTC, sheenarbw commented on backend/curriculum_tracking/tests/test_activity_log_entry_creators.py
> +        creators.EventType.objects.get_or_create(name=creators.CARD_MOVED_TO_REVIEW_FEEDBACK)
These tests shouldn't need to be updated.

If you make your sql queries more efficient then these changes wont be required.

2022-12-08 07:32 UTC, sheenarbw commented on backend/curriculum_tracking/serializers.py
> +            event_type=EventType.objects.get(name='CARD_MOVED_TO_REVIEW_FEEDBACK')),
This query results in multiple SQL queries being fired off. We could mke this more efficient by doing something like:

```
filter(event_type__name=CARD_MOVED_TO_REVIEW_FEEDBACK)
```

2022-12-08 07:32 UTC, sheenarbw commented on backend/curriculum_tracking/tests/test_api_views.py
> +        creators.EventType.objects.get_or_create(name=creators.CARD_MOVED_TO_REVIEW_FEEDBACK)
These changes shouldn't be needed

2023-08-14 09:59 UTC, closed without merging