agile-card-actions-logic
Umuzi-org/Tilde pull request #626
Opened 2022-09-29 10:34 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-05 15:08 UTC, Ngoakor12 requested changes
Actions still seem to work fine :ok_hand: 
- File extensions don't match the [styleguide.md](https://github.com/Umuzi-org/Tilde/blob/develop/frontend/STYLE_GUIDE.md#naming-files-and-directories)

2022-10-05 15:08 UTC, Ngoakor12 commented on frontend/src/components/regions/AddCardReviewModal/Presentation.jsx
> +                minRows={5}
this seems to have changed the visuals of the modal? which I don't think was intentional, see image:
![image](https://user-images.githubusercontent.com/54069197/194094352-6580871b-caf4-46fb-a450-9d165b0120cf.png)

2022-10-06 06:43 UTC, Ngoakor12 commented
> * File extensions don't match the [styleguide.md](https://github.com/Umuzi-org/Tilde/blob/develop/frontend/STYLE_GUIDE.md?rgh-link-date=2022-10-05T15%3A08%3A40Z#naming-files-and-directories)

You missed this :point_up:

2022-10-06 08:52 UTC, Ngoakor12 approved these changes

2022-10-19 12:37 UTC, Ngoakor12 approved these changes

2022-10-21 11:48 UTC, KhalidUmuzi approved these changes

2022-10-23 02:00 UTC, sheenarbw requested changes
It's a start but there is still a lot to do.

AgileCardActions needs to take in minimal props - maybe just the card and the authuser
index.jsx should then implement all of the handlers needed to make the actions work

Is there some reason to keep some of the AgileCardActions functionality in the parent component?

2022-10-23 02:00 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/AgileCard/AgileCardActions/index.jsx
> +import React from "react";
when renaming files can you please just rename them in place instead of deleting and recreating the file? It makes reviewing PRs much easier. 

If you look at this PR then it looks like you wrote all the code in this file from scratch. So for me to see what changed is really hard.

2022-10-23 02:00 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/AgileCard/Presentation.jsx
> -    authUser,
Ideally AgileCardActions should not have so much logic passed ni from the outside. 

It should just know about the card we are looking at, and possibly the authuser. Mnimise the props as much as possible.

2022-10-23 02:00 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/AgileCard/index.jsx
> +  handleClickOpenWorkshopAttendanceForm,
The agileCard shouldn't need any props related to the buttons.

2022-10-23 02:00 UTC, sheenarbw commented on frontend/src/components/regions/AgileBoard/AgileCard/AgileCardActions/index.jsx
> +  handleClickOpenCardDetails,
Please make sure that handlers are implemented in the correct component as much as possible.

2022-10-27 08:34 UTC, FaithMo commented on frontend/src/components/regions/AgileBoard/AgileCard/AgileCardActions/index.jsx
> +import React from "react";
Actually I changed the name of the file only. I did not delete it.

2022-10-27 13:04 UTC, Ngoakor12 approved these changes

2022-11-02 01:13 UTC, KhalidUmuzi approved these changes

2022-11-09 08:47 UTC, sheenarbw approved these changes

2022-11-09 08:48 UTC, merged