accordion for reviewers list
Umuzi-org/Tilde pull request #639
Opened 2022-11-04 19:29 UTC by TheMaja

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-09 08:02 UTC, Ngoakor12 requested changes
Visuals look good Themba,

- But I get this error whenever I try and start the frontend:
![image](https://user-images.githubusercontent.com/54069197/200769652-dcbe7105-dcd0-49ab-bebf-629cead298ba.png)
Did you perhaps make any changes to the package.json for it to work? I'm asking because the accordion components(`AccordionSummary` and `AccordionDetails`) don't seem to be available on this mui version from even after `npm install`
- I was able to get it to show up with a different mui version (`v4.12.4`)
  - Could the "Reviewers" text be the same size as "Assignees" text? Same thing with the email addresses in the "Assignees" and "Reviewers" section

2022-11-09 08:36 UTC, TheMaja commented
> Visuals look good Themba,
> 
> * But I get this error whenever I try and start the frontend:
>   ![image](https://user-images.githubusercontent.com/54069197/200769652-dcbe7105-dcd0-49ab-bebf-629cead298ba.png)
>   Did you perhaps make any changes to the package.json for it to work? I'm asking because the accordion components(`AccordionSummary` and `AccordionDetails`) don't seem to be available on this mui version from even after `npm install`
> * I was able to get it to show up with a different mui version (`v4.12.4`)
>   
>   * Could the "Reviewers" text be the same size as "Assignees" text? Same thing with the email addresses in the "Assignees" and "Reviewers" section

Thanks for the review @Ngoakor12 
Tilde uses `@material-ui` just take a look at all the libraries below 
![image](https://user-images.githubusercontent.com/73611175/200777060-ef91559b-8ef1-4e8f-a12f-0df579176de5.png)
Mui is version 5 and i haven't seen it being used here, for compatibility with the rest of the codebase i am using v4 what is being used on the rest of Tilde frontend. 
- as for the `assignees` and `reviewers` being the same size yes that's is possible but for the `email addresses` that is not possible because its inside an accordion and also we trying to avoid a situation whereby an email address does not fit inside a card like the situation below. 
![image](https://user-images.githubusercontent.com/73611175/200779877-d813dbc2-b941-42fe-966d-148e045db874.png)

2022-11-09 09:06 UTC, Ngoakor12 commented
Okay cool, can you just address the merge conflicts first?

2022-11-09 15:29 UTC, Ngoakor12 approved these changes

2022-11-10 16:17 UTC, Vuyisanani approved these changes

2023-08-14 09:59 UTC, closed without merging