moved teamviewset from core to curriculum tracking + tests
Umuzi-org/Tilde pull request #644
Opened 2022-11-29 14:24 UTC by Andy-Nkumane

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-11-30 22:48 UTC, Rokhuda approved these changes

2022-12-01 07:59 UTC, sheenarbw requested changes
Hmm. You moved too many things. You'll need to put some stuff back.

The reason that the viewset needs to move is because the core app should not depend on the curriculum tracking app. The curriculum tracking app can depennd on the core app though. 

The Team viewset NEEDS to depend on curriculum_tracking, that's why it is moving.  Putting the tests in a totally different app wouldn't makde any sense. So the viewset tests need to move too.

But moving absolutely everything indiscriminately wont help our technical debt much.

2022-12-01 07:59 UTC, sheenarbw commented on backend/core/tests/factories.py
> -class TeamFactory(DjangoModelFactory):
This is a factory, not a viewset test. 

Please put this one back.

2022-12-01 07:59 UTC, sheenarbw commented on backend/core/tests/test_user.py
> +from curriculum_tracking.tests.factories import TeamFactory
Please don't move the factories.

Only:
- the viewset
- the tests for the viewset

2022-12-06 09:59 UTC, Rokhuda approved these changes

2022-12-08 07:17 UTC, sheenarbw approved these changes

2022-12-08 07:17 UTC, merged