Add tests on pull request template
Umuzi-org/Tilde pull request #649
Opened 2022-12-13 12:35 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-12-13 13:33 UTC, Ngoakor12 reviewed
I think this is already covered in the last point in the checklist, no?

2022-12-13 14:50 UTC, FaithMo commented
> I think this is already covered in the last point in the checklist, no?

this is if you have added tests to any feature you have done, but the one I added makes emphasis on tests that either exist before your feature or that you have added and do not break something ...

2022-12-13 15:31 UTC, Ngoakor12 commented
> > I think this is already covered in the last point in the checklist, no?
> 
> this is if you have added tests to any feature you have done, but the one I added makes emphasis on tests that either exist before your feature or that you have added and do not break something ...

But this means we'll now have three points on the checklist related to tests... I don't think it's bad but maybe it's redundant and can be summarised better?
- the first point about tests is for adding tests 
- the second test related point is about if both the old and new pass

Would changing the existing last point to just  "**New and existing unit tests pass locally**" be better than adding a slightly similar point? I think it covers new and old test well

2022-12-14 05:50 UTC, FaithMo commented
> > > I think this is already covered in the last point in the checklist, no?
> > 
> > 
> > this is if you have added tests to any feature you have done, but the one I added makes emphasis on tests that either exist before your feature or that you have added and do not break something ...
> 
> But this means we'll now have three points on the checklist related to tests... I don't think it's bad but maybe it's redundant and can be summarised better?
> 
> * the first point about tests is for adding tests
> * the second test related point is about if both the old and new pass
> 
> Would changing the existing last point to just "**New and existing unit tests pass locally**" be better than adding a slightly similar point? I think it covers new and old test well

makes sense. otherwise just leave it as is? cause it covered the same thing?

2022-12-14 07:07 UTC, Ngoakor12 requested changes

2022-12-14 07:07 UTC, Ngoakor12 commented on pull_request_procedure.md
>  - [ ] I have tested new or existing tests and made sure that they pass
using "or" on the "new or existing" part of the sentence makes it sounds like you should choose one or the other

2022-12-14 09:30 UTC, FaithMo commented on pull_request_procedure.md
>  - [ ] I have tested new or existing tests and made sure that they pass
i thought of it as "I have tested new tests" (if I created new tests) or "I have tested existing tests" (if I have not added any tests, to make sure nothing breaks)

2022-12-14 09:58 UTC, Ngoakor12 approved these changes

2023-01-04 12:37 UTC, sheenarbw approved these changes

2023-01-04 12:37 UTC, merged