Add assertions for running tag, no repeated tags, and import learner code
Umuzi-org/Tilde pull request #672
Opened 2023-11-18 22:40 UTC by kingraphaii

Ref: [https://umuzi-projects.monday.com/boards/1254743632/pulses/1261667339](https://umuzi-projects.monday.com/boards/1254743632/pulses/1261667339)

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2023-11-21 10:26 UTC, Ngoakor12 approved these changes

2023-11-22 04:02 UTC, sheenarbw requested changes
Some stuff in here is much more complicated than it needs to be. Always aim for the simplest code possible.

2023-11-22 04:02 UTC, sheenarbw commented on automarker_2/automarker_app/lib/automarker_test_runner.py
> +            re.search(rf"<{TAG_RUNNING}>", self.last_command_output.stdout)
Why does this work differently to assert_command_description_present? Why only check for opening tags and not closing tags?

2023-11-22 04:02 UTC, sheenarbw commented on automarker_2/automarker_app/lib/utils.py
> +    class NewRunnerCls(cls):
KISS

Surely there is a simpler way to do inheritance? 

If most things expect import tags then this should be in the base class, then just override the method where needed

2023-11-23 10:36 UTC, kingraphaii commented on automarker_2/automarker_app/lib/automarker_test_runner.py
> +            re.search(rf"<{TAG_RUNNING}>", self.last_command_output.stdout)
### Sample `__dict__` of `self.last_command_output`:
```python
{
    "stdout": '<setup>\n</setup>\n<command_description>\nconstruct a two Homes (home1, home2); adopt the animal (cat1) in both homes; then make all sounds in both homes\n</command_description>\n<import_learner_code>\n</import_learner_code>\n<running>\n</running>\n<returned>\n{"adopt_home_one":1,"adopt_home_two":1,"sounds_home_one":["Meow"],"sounds_home_two":["Meow"]}\n</returned>\n',
    "stderr": "",
    "setup": "",
    "import_learner_code": "",
    "running": "",
    "returned": {
        "adopt_home_one": 1,
        "adopt_home_two": 1,
        "sounds_home_one": ["Meow"],
        "sounds_home_two": ["Meow"],
    },
    "command_description": "construct a two Homes (home1, home2); adopt the animal (cat1) in both homes; then make all sounds in both homes",
}
```

If we do `assert self.last_command_output[TAG_RUNNING]` it will fail as per:

```python
>>> d = {"a": ""}
>>> assert d["a"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

but for command description it will work because we actually expect some output in there.

So some tags' blocks will not have any output, as shown in the sample even though they're properly setup. This is why I resorted to checking the `stdout` instead. I know even in doing so, there's room for improvement, but I just wanted to confirm If I'm getting this right.

2023-11-23 10:52 UTC, sheenarbw commented on automarker_2/automarker_app/lib/automarker_test_runner.py
> +            re.search(rf"<{TAG_RUNNING}>", self.last_command_output.stdout)
Ok cool. That makes sense.
Maybe just check that there is an opening and closing tag.

2023-11-24 06:19 UTC, Ngoakor12 requested changes

2023-11-24 06:19 UTC, Ngoakor12 commented on automarker_2/automarker_app/lib/automarker_test_runner.py
> +                len(self.last_command_output.unfinished_tags()) == 0
I think the assertion message is a bit confusing. How about something like `expected tags to be closed but the following tags appear to be left open:...`

2023-11-24 08:03 UTC, Ngoakor12 approved these changes

2023-11-24 10:08 UTC, sheenarbw approved these changes

2023-11-24 10:08 UTC, merged