Add tests for forgot password and login/logout
Umuzi-org/Tilde pull request #678
Opened 2024-01-07 20:22 UTC by kingraphaii

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-01-08 07:25 UTC, Ngoakor12 requested changes

2024-01-08 07:25 UTC, Ngoakor12 commented on backend/frontend/tests/frontend_test_mixin.py
>          # TODO: Update this so it works with the new login page
Please remove this comment because you seem to have addressed it.

2024-01-12 05:38 UTC, Ngoakor12 approved these changes

2024-01-12 08:51 UTC, sheenarbw approved these changes
Weee!

2024-01-12 08:51 UTC, merged