Fix: Frozen Modules Bug when marking pandas projects
Umuzi-org/Tilde pull request #684
Opened 2024-01-15 11:49 UTC by kingraphaii

## Description:

﻿When marking or running a config check for jupyter notebook projects, a breakpoint is hit because [we expect a certain length of the output](https://github.com/Umuzi-org/Tilde/blob/60c050b0702eb9aef63e758ad973eea2dfcf041a/automarker_2/automarker_app/lib/steps.py#L767C2-L767C2) from the NbConvert cmd. This happens when Python prints out some warnings, as shown in the screenshot below.﻿﻿

﻿
![big-image](https://github.com/Umuzi-org/Tilde/assets/57295227/a349574f-3d15-4179-9199-874a7e038387)

This fix only checks if the output we need is present in the output irregardless of the out. length

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested new or existing tests and made sure that they pass

2024-01-16 14:08 UTC, Ngoakor12 approved these changes

2024-01-17 13:26 UTC, sheenarbw requested changes
Just one thing that can be made clearer

2024-01-17 13:26 UTC, sheenarbw commented on automarker_2/automarker_app/lib/steps.py
> +                if not start_line_present or not end_line_present:
Isn't this equivalent and easier to read?

```
if not(start_line_present and end_line_present):
```

We want the start and end to be present. If they are not both present then it means something funny is happening, right?

2024-01-18 17:15 UTC, Ngoakor12 approved these changes

2024-01-22 09:46 UTC, sheenarbw approved these changes

2024-01-22 09:47 UTC, merged