Differentiate a blocked card from a ready card
Umuzi-org/Tilde pull request #685
Opened 2024-01-15 13:20 UTC by Raymond-Mawina

Related issues: [please specify]

## Description:

Mom link: [card_component: Make it clear when a card is blocked versus ready](https://umuzi-projects.monday.com/boards/1274815998/pulses/1301469421)

## Screenshots/videos

- I used the color `'grey'` to indicate that the card is a blocked-card.

![Screenshot 2024-01-15 151805](https://github.com/Umuzi-org/Tilde/assets/94048861/626a3b76-6e58-46f2-979e-ca12d752a5e4)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-01-16 13:53 UTC, Ngoakor12 requested changes
This seems fine but I think the colour is a bit too closer to blue than it should be.

Maybe try the other grey-ish -200 colours below slate? [Here's a reference](https://tailwindcss.com/docs/customizing-colors)

2024-01-16 14:50 UTC, Ngoakor12 approved these changes

2024-01-16 14:56 UTC, Ngoakor12 approved these changes

2024-01-17 12:54 UTC, sheenarbw commented
Can you deactivate the "start" button as well please? It looks like it can still be clicked.

2024-01-17 14:47 UTC, Ngoakor12 commented
> Can you deactivate the "start" button as well please? It looks like it can still be clicked.

@sheenarbw the above button only shows when a card can be "force started" and a user has the permission to "force start" the card. Otherwise, the button doesn't show up on blocked cards at all(see image):

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/d82af138-05ad-4c85-b8bd-0f904d68ba0a)


So I'm wondering if this change is necessary?

2024-01-18 11:01 UTC, sheenarbw approved these changes

2024-01-18 11:01 UTC, merged