profile menu collapsable
Umuzi-org/Tilde pull request #694
Opened 2024-01-25 10:16 UTC by TheMaja

- profile click dropdown menu
- dropdown menu working
- mobile menu updated

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-01-26 08:41 UTC, Ngoakor12 requested changes
On the right track Themba...just a few things

- I like how smooth the opening animation is :slightly_smiling_face: 
- The menu opens the wrong way(to the right) on larger screens causing the website to break/go out of bounds. Please just use original position( where it opens to the left) and  make sure clicking the profile icon closes or opens it.
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/68f3bc35-ac84-418d-aec2-2a67a2ac5365)
> original

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/e84596d0-7706-4ecd-9f0d-f2d7654aa176)
> current 

- The way the menu shows on the smaller screens got slightly worse. Please stick with the original layout
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/9258e1b8-77ad-477d-82da-0eb86b83c8e7)
> original

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/c0bc9b8b-2418-4c59-a7cc-d5f197c8885a)
> current

- Remember to make sure that clicking the hamburger icon still closes or opens the menu on the smaller screens.

2024-01-30 11:29 UTC, Ngoakor12 requested changes
Mostly good Themba,

One tiny thing...
The hover background should have matching rounded corners when you're hovering or not hovering on the first and last option in the dropdown menu.

E.g. The top left and right should have a border-radius so that the corners are rounded. 
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/c455c042-c9d2-4661-b2d3-d9fe23584640)

2024-02-01 07:46 UTC, Ngoakor12 approved these changes

2024-02-05 12:31 UTC, sheenarbw requested changes
Just one thing I could find

2024-02-05 12:31 UTC, sheenarbw commented on backend/frontend/templates/frontend/base_logged_in.html
> +    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
frontend/templates/frontend/base.html includes the line:

```
    <script src="https://cdn.tailwindcss.com"></script>
```

And this template extends base.

Why are you including tailwind again? And why should different parts of the website run different versions of tailwind?

2024-02-09 08:59 UTC, sheenarbw approved these changes

2024-02-09 08:59 UTC, merged