Remove everything to do with topic_needs_review
Umuzi-org/Tilde pull request #698
Opened 2024-02-12 21:24 UTC by Ngoakor12

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-02-14 09:33 UTC, kingraphaii reviewed
LGTM

I have a question though, there's still some refs in the "export_curriculum.py" and "import_curriculum.py" scripts. ["topic_needs_review": o.topic_needs_review,](https://github.com/Umuzi-org/Tilde/blob/c1a4e3876c6a804f15f2c7679f0a6b3b55189bb8/backend/curriculum_tracking/management/commands/export_curriculum.py#L72), [topic_needs_review](https://github.com/Umuzi-org/Tilde/blob/c1a4e3876c6a804f15f2c7679f0a6b3b55189bb8/backend/curriculum_tracking/management/commands/import_curriculum.py#L60), should we not remove those too

2024-02-14 10:02 UTC, Ngoakor12 commented
> LGTM
> 
> I have a question though, there's still some refs in the "export_curriculum.py" and "import_curriculum.py" scripts. ["topic_needs_review": o.topic_needs_review,](https://github.com/Umuzi-org/Tilde/blob/c1a4e3876c6a804f15f2c7679f0a6b3b55189bb8/backend/curriculum_tracking/management/commands/export_curriculum.py#L72), [topic_needs_review](https://github.com/Umuzi-org/Tilde/blob/c1a4e3876c6a804f15f2c7679f0a6b3b55189bb8/backend/curriculum_tracking/management/commands/import_curriculum.py#L60), should we not remove those too

My thinking was that we already had the objects fetched from the above lines and that accessing them while they're already fetched shouldn't make any new db calls. But I've changed it anyway, just in case.

2024-02-14 13:19 UTC, kingraphaii approved these changes

2024-02-14 16:16 UTC, sheenarbw requested changes
This is good, but it's incomplete. 

Ther is a topic_needs review field on the ContentItem model. There are a whole lot of things that expect that column to exist.  All that stuff must go.

If you are running vscode, open the backend directory and Ctrl+Shift+F to find all mentions of topic_needs_review.  Those should all. The only mentions that can remain are those in the api serialisers. Everything else is technical debt

2024-02-14 16:16 UTC, sheenarbw commented on backend/curriculum_tracking/models.py
>      def topic_needs_review(self):
This function can be deleted. It's really just the api serialisers that need to hold onto topic_needs_review stuff.

2024-02-14 16:16 UTC, sheenarbw commented on backend/curriculum_tracking/models.py
>      def topic_needs_review(self):
There is more stuff that needs to be removed in this file. 

Eg:
```
topic_needs_review = models.BooleanField(default=False)
```

It should be like topic_needs_review does not exist at all. We just leave a little bit of a ghost in the apis so the old frontend doesnt freak out.

If you do a full search over the entire backend and topic_needs_review comes up at all then the algorithm for each instance is:

```
if we are looking at an api serialiser:
     just set it to false
else:
    remove it
```

2024-02-14 16:16 UTC, sheenarbw commented on backend/curriculum_tracking/models.py
> -            self.topic_progress.review_request_time = timezone.now()
Can you please make a seperate task to remove topic.review_request_time as well since people cant request reviews on topics. And the whole TopicReview model as well... 

I figure that work can happen later on, we can just chip away at technical debt over time

2024-02-14 16:16 UTC, sheenarbw commented on backend/curriculum_tracking/tests/test_api_views.py
> +        content.topic_needs_review = False
this line should be deleted since it isn't in an api serializer

2024-02-27 07:17 UTC, kingraphaii requested changes
A bunch of tests are failing because of the recent changes.

2024-02-27 09:03 UTC, Ngoakor12 commented
> A bunch of tests are failing because of the recent changes.

My bad, I'll have a look. I believe I just ran the frontend tests

2024-02-27 11:55 UTC, Ngoakor12 commented
That should do it. Please reply with screenshots if the issue still persists so I know which tests are giving you issues

2024-02-28 06:27 UTC, kingraphaii commented
Here is one of them, basically ran `python manage.py test` to test everything:


```traceback
..[Tilde-backend] [2024-02-28 06:27:11] INFO [logging_middleware:21] anonomous [GET] /api/activity_log_entries/
E
======================================================================
ERROR: test_get_list (activity_log.tests.test_api_views.TestLogEntryViewSet.test_get_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "topic_needs_review" violates not-null constraint
DETAIL:  Failing row contains (1, P, something awesome part 1, something-awesome-part-1, https://raw.githubusercontent.com/Umuzi-org/tech-department/mast..., null, R, https://github.com/Umuzi-org/bwahahhahaaaa, null, null, t, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kingraphaii/Dev/Tilde/backend/test_mixins.py", line 48, in test_get_list
    instance = self.verbose_instance_factory()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/activity_log/tests/test_api_views.py", line 111, in verbose_instance_factory
    card = AgileCardFactory()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/base.py", line 40, in __call__
    return cls.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/django.py", line 121, in _generate
    return super()._generate(strategy, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/base.py", line 465, in _generate
    return step.build()
           ^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 270, in build
    step.resolve(pre)
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 211, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 356, in __getattr__
    value = value.evaluate_pre(
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/declarations.py", line 67, in evaluate_pre
    return self.evaluate(instance, step, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/declarations.py", line 457, in evaluate
    return step.recurse(subfactory, extra, force_sequence=force_sequence)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 228, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 270, in build
    step.resolve(pre)
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 211, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 356, in __getattr__
    value = value.evaluate_pre(
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/declarations.py", line 67, in evaluate_pre
    return self.evaluate(instance, step, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/declarations.py", line 457, in evaluate
    return step.recurse(subfactory, extra, force_sequence=force_sequence)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 228, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/builder.py", line 274, in build
    instance = self.factory_meta.instantiate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/factory/django.py", line 174, in _create
    return manager.create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/kingraphaii/Dev/Tilde/backend/curriculum_tracking/models.py", line 318, in save
    super(ContentItem, self).save(*args, **kwargs)
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/Users/kingraphaii/Dev/Tilde/backend/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_ [...]

2024-02-28 06:55 UTC, Ngoakor12 commented
I don't have any issues running all the tests now.

I believe those errors arise because the PR changes the model properties, so migrations must be made.

Running:
```sh
python manage.py makemigrations && python manage.py migrate
```
should resolve the issues.

2024-02-28 07:18 UTC, kingraphaii approved these changes

2024-03-01 05:33 UTC, sheenarbw approved these changes

2024-03-01 05:33 UTC, merged