bugfix user teams next button
Umuzi-org/Tilde pull request #699
Opened 2024-02-15 20:39 UTC by TheMaja

- test that exposes the  button bug
- bug fixed and test is passing

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-02-16 20:09 UTC, Ngoakor12 requested changes
Looks good

- Start button text with capital letter
- Use a normal width button to keep everything consistent. I think the only full-width buttons I've seen are the cards and they're in the process of being changed.

2024-02-26 08:18 UTC, Ngoakor12 approved these changes

2024-02-26 08:22 UTC, Ngoakor12 approved these changes

2024-02-26 14:33 UTC, sheenarbw approved these changes

2024-02-26 14:33 UTC, merged