Fix/allow indirectly permissioned collaborators
Umuzi-org/Tilde pull request #700
Opened 2024-02-16 08:07 UTC by kingraphaii

Related issues: [please specify]
[https://umuzi-projects.monday.com/boards/1274815998/pulses/1395525297](https://umuzi-projects.monday.com/boards/1274815998/pulses/1395525297)

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested new or existing tests and made sure that they pass

2024-02-16 20:54 UTC, Ngoakor12 requested changes

2024-02-16 20:54 UTC, Ngoakor12 commented on backend/core/tests/test_add_github_collaborator_permission_check.py
> +            Team.PERMISSION_MANAGE_CARDS,
This doesn't change much, but should it not be `Team.PERMISSION_REVIEW_CARDS`. We are adding them as a collaborator/reviewer not a manager right?

2024-02-27 06:44 UTC, kingraphaii commented on backend/core/tests/test_add_github_collaborator_permission_check.py
> +            Team.PERMISSION_MANAGE_CARDS,
I just picked one from the permission set which determines who get to be a collaborator, and manage_cards perm is part of that. Refer to:

[PERMISSION_REPO_COLLABORATER_AUTO_ADD](https://github.com/Umuzi-org/Tilde/blob/fe6a819f22bd8bb9ad95ec4aef9d973daa159cff/backend/core/models.py#L253)

2024-02-27 09:00 UTC, Ngoakor12 approved these changes
Yeah it's not a big issue functionally, I just thought it would make more sense to use the other one seeing that we are referring to a reviewer in our last test

2024-02-28 05:46 UTC, sheenarbw approved these changes

2024-02-28 05:46 UTC, merged