[WIP] -- add details button to the card component
Umuzi-org/Tilde pull request #701
Opened 2024-02-28 08:55 UTC by Raymond-Mawina

Related issues: Link to task on mom: [card_component: add "details" button](https://umuzi-projects.monday.com/boards/1274815998/pulses/1301320895)

## Description:

- **These are the requirements**:
  1. This should be a link that looks like a button.
  1. t should redirect to topics/{topic_id} or projects/{project_id}.
  1. It should link directly to the topic or project progress instance.
  1. In Tilde 1, we link to a page like card/{card_id}. This is a problem because card ids are ephemeral, and the whole card creation mechanism needs to be rethought.

- **This is the plan**:
  - I will code this TDD style
  - I will add the tests which will fail.
  - I will add code that will make the tests pass.
  - I will refactor the code for cleanup purposes.
  - Finally, I will open an official PR and request a review on Mom. 

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-03-07 07:40 UTC, kingraphaii requested changes

2024-03-07 07:40 UTC, kingraphaii commented on backend/backend/settings.py
> +    # "project_review_coordination",
DOnt forget to put this back

2024-03-07 07:40 UTC, kingraphaii commented on backend/frontend/tests/frontend_test_mixin.py
> +        return f"{self.live_server_url}{end}"
Why was this necessary? `is there somwhere we hardcoded  URLs?

2024-03-07 08:47 UTC, Raymond-Mawina commented on backend/frontend/tests/frontend_test_mixin.py
> +        return f"{self.live_server_url}{end}"
@kingraphaii, I think it is necessary. When I run the tests like this: `python mange.py test,` My test fails when the forward slash is included. I found out that the variable `end` in the method `reverse_url` already comes with a forward slash, so I am trying to remove the extra forward slash.

![Screenshot 2024-03-07 103737](https://github.com/Umuzi-org/Tilde/assets/94048861/b526ae41-7fd6-459d-bb8e-c6cae19a559b)


Is there something I am missing?

2024-03-07 09:06 UTC, kingraphaii approved these changes

2024-03-07 09:08 UTC, kingraphaii requested changes

2024-03-07 09:08 UTC, kingraphaii commented on backend/frontend/templates/frontend/user/board/partial_card.html
> +        <div class="Details-button col-span-1 row-span-1 w-full">
The class naming casing is wrong here, also, are really using that class anywhere?

2024-03-07 09:38 UTC, kingraphaii approved these changes

2024-03-08 07:13 UTC, sheenarbw approved these changes

2024-03-08 07:13 UTC, merged