card component: Add "done" button
Umuzi-org/Tilde pull request #704
Opened 2024-03-04 20:50 UTC by kingraphaii

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested new or existing tests and made sure that they pass

2024-03-05 10:41 UTC, Ngoakor12 requested changes

2024-03-05 10:41 UTC, Ngoakor12 commented on backend/frontend/tests/test_card_done_button.py
> +        ip_topic_card = self.page.text_content("div#column_IP")
This tests passes and fails sometimes:
```
FAIL: test_done_button_shows_for_topic_cards (frontend.tests.test_card_done_button.TestCardDoneButton)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/frontend/tests/test_card_done_button.py", line 59, in test_done_button_shows_for_topic_cards
    self.assertIn("Done", ip_topic_card)
AssertionError: 'Done' not found in ''

----------------------------------------------------------------------
Ran 5 tests in 16.595s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

Waiting before selecting seems to resolve it:
```
self.page.wait_for_load_state("networkidle")
```

2024-03-06 07:59 UTC, Ngoakor12 commented on backend/frontend/tests/test_card_done_button.py
> +        ip_topic_card = self.page.text_content("div#column_IP")
Still failing occasionally, You have to wait for everything to load before selecting the column, not after the selection of ip_column.

2024-03-06 14:15 UTC, Ngoakor12 approved these changes

2024-03-08 07:09 UTC, sheenarbw approved these changes

2024-03-08 07:09 UTC, merged