Link project: allow user to update the submission link
Umuzi-org/Tilde pull request #706
Opened 2024-03-06 23:31 UTC by Raymond-Mawina

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-03-08 07:14 UTC, Ngoakor12 requested changes
Functionality seems good...

- The edit icon needs a tool-tip because it won't be obvious to everyone or maybe just use a normal text button
- Clicking the open space on the right side of the button should not click the button
- The page should be responsive in smaller screens:
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/5a858566-13cc-4eec-a6a2-1c376acfe2c6)


- Another stylistic change I think should be made is replacing the "Course Component Details" text with the actual title of the project and removing it from the field below so it doesn't come up twice 
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/e7e19b6d-2333-42fb-9652-c4fffb20d2d9)

2024-03-08 07:25 UTC, Ngoakor12 requested changes

2024-03-08 07:25 UTC, Ngoakor12 commented on backend/frontend/tests/test_course_component_details_pages.py
> +    def test_link_submission_form_correctly_updates_link_submission_after_link_update(
change `test_link_submission_form_correctly_updates_link_submission_after_link_update` to `test_link_submission_form_correctly_updates_link_submission` or make it less confusing

2024-03-08 07:25 UTC, Ngoakor12 commented on backend/frontend/tests/test_course_component_details_pages.py
> +        body = self.page.text_content("body")
You may also want to preemptively wait for everything to load before selecting any text_contethis tends to cause failing tests if something is selected while things haven't fully loaded. You can look up examples in other tests or maybe there's a better way

2024-03-14 06:15 UTC, Ngoakor12 requested changes
Mostly good, just make sure the edit button is also responsive and does not continue to shrink in the way it's doing.

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/7fe846b9-08de-4661-acfe-2a77407a84aa)


Adding a `max-w-max` instead of `w-1/6` resolves the issue

2024-03-14 07:28 UTC, Ngoakor12 approved these changes

2024-03-14 09:00 UTC, sheenarbw requested changes
Please keep script tags dry. 

Look at the duplicated script tags in all logged in pages.  If we inherit from a template, and a thing is defined in that template, we dont need to define it again.

2024-03-14 09:00 UTC, sheenarbw commented on backend/frontend/templates/frontend/base.html
> +    <script
This is interesting. Don't we also include alpine.js in other templates? 

So now those templates that inherit from this one will include alpinejs twice. 

Please keep it DRY.

2024-03-14 17:42 UTC, Ngoakor12 approved these changes

2024-03-15 06:50 UTC, sheenarbw reviewed
This seems a bit overly complicated in a few ways. Implementing and testing the hiding and showing of forms was complex and unnecessary. I'm not sure that the UX makes sense - I mean, why have the extra clicks? The showing and hiding doesn't seem to add much value. 

The form is literally one field and one button. It's pretty small. It's not a big, bulky thing taking up all the space and making the page all cluttered. Replacing it with a big giant button and making the user click extra is a bit of a funny thing to do. 

If there is a link filled in: 
- Just display the link
- also display a pre-filled form for changing the link 

if there is no link filled in:
- display a pre-filled form for setting the link

There is a thing in coding called KISS. It's worth looking up.

Can you please simplify this. 

The one bit of fanciness that probably does make sense would be to use HTMX to submit the forms and then just swap the form out in place instead of reloading the entire page. But I would be ok with deferring that

2024-03-20 07:00 UTC, sheenarbw approved these changes

2024-03-20 07:01 UTC, merged