admin button delete recreate cards entire team
Umuzi-org/Tilde pull request #719
Opened 2024-04-04 12:32 UTC by TheMaja

- **delete recreate class udjusted for teams**
- **delete and recreate cards for team**

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-04-04 17:13 UTC, Ngoakor12 requested changes
Functionality looks as expected

2024-04-04 17:13 UTC, Ngoakor12 commented on backend/core/templates/admin/core/confirm_delete_recreate_cards.html
> -        <form action="{% url 'confirm_delete_recreate_cards' user.id %}" method="post">
This breaks the functionality on the PR you got merged last time.

2024-04-05 10:00 UTC, Ngoakor12 approved these changes

2024-04-07 09:58 UTC, sheenarbw approved these changes

2024-04-07 09:58 UTC, merged