display all reviewers on agile card
Umuzi-org/Tilde pull request #724
Opened 2024-04-15 14:24 UTC by TheMaja

- dropdown review list created, what happens to the space of the old review div?
- dropdown review list moved to topleft position in card
- bold text on reviewers list

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have merged the develop branch into my branch and fixed any merge conflicts
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested new or existing tests and made sure that they pass

2024-04-16 06:06 UTC, Ngoakor12 approved these changes
The PR achieves what it set out to do.

I do, however believe this is a much worse experience than displaying the reviewers like they were before the avatars. But that can be changed in the future.

2024-04-16 08:35 UTC, Sbonelo01 requested changes
The entire reviewer list gets displayed which is good. But, it's displayed in the wrong place.

Please note that currently, a tool tip is able to display all the reviewers aswell. What we basically want to do is replace the tool tip with a drop down.

Please see the image below to get an idea of what would look better. The portion I circled in green is what it would ideally look like, whilst the section I circled in red is what your current PR introduces to the card

![ideal look](https://github.com/Umuzi-org/Tilde/assets/37469171/abd9e0a9-e5ff-4bd4-ac32-a0b574e4a94d)

2024-04-19 09:23 UTC, Sbonelo01 approved these changes
Looks good, it can be improved later on, 

I see @Ngoakor12 's change to the avatars makes us see only 2 reviewer avatars instead of 3, like before. 

The absence of a 3rd anonymous avatar makes it difficult for me to give you more constructive feedback right now because my thinking was that the 3rd avatar becomes an anonymous avatar **if there are more than 3 reviewers on the card**, and hovering this 3rd avatar displays the dropdown.

I will approve. Sheena can advise further.

2024-04-19 14:05 UTC, sheenarbw reviewed
It achieves what it should but I wouldn't want to put this in front of our learners. 

If we can't get a nice hover effect, then we should just display all the reviewers all of the time.

2024-04-25 11:48 UTC, Ngoakor12 requested changes
I get the following in the terminal when opening a user's board, and the cards don't load
```
Traceback (most recent call last):
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/frontend/views.py", line 106, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/frontend/views.py", line 328, in view_partial_user_board_column
    return render(
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'progress_details' not found. 'progress_details' is not a valid view function or pattern name.
[Tilde-backend] [2024-04-25 11:47:00] ERROR [django.request:224] Internal Server Error: /users/17/board/C
Traceback (most recent call last):
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/frontend/views.py", line 106, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/frontend/views.py", line 328, in view_partial_user_board_column
    return render(
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist [...]

2024-04-25 12:00 UTC, Sbonelo01 commented
@TheMaja I also mentioned that I get the same error that @Ngoakor12 stated. Can I take over this task as per @sheenarbw 's suggestion? I'll create a different branch but I'll take some of the code you've written so it does not go to waste.

2024-04-25 13:11 UTC, TheMaja commented
> @TheMaja I also mentioned that I get the same error that @Ngoakor12 stated. Can I take over this task as per @sheenarbw 's suggestion on MoM? I'll create a different branch but I'll take some of the code you've written so it does not go to waste.

issue resolved had to do with my branch being outdated

2024-04-25 13:14 UTC, TheMaja commented
> > @TheMaja I also mentioned that I get the same error that @Ngoakor12 stated. Can I take over this task as per @sheenarbw 's suggestion on MoM? I'll create a different branch but I'll take some of the code you've written so it does not go to waste.
> 
> Issue resolved. It had to do with my branch being outdated. @Sbonelo01 resolved okay you will take over after it has been merged or if issues are raised afterwards by @sheenarbw

2024-04-25 15:05 UTC, Ngoakor12 requested changes
@TheMaja now it shows up like this instead:
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/466b19ec-f75a-4cb7-a634-4b2d88d60050)

Also, the tooltip for the assignee vs reviewers are very different, which is not ideal.

2024-04-25 15:07 UTC, Ngoakor12 commented
I'm also in favour of @Sbonelo01 taking over, as was suggested before.

2024-04-26 15:15 UTC, Sbonelo01 commented
Video:


https://github.com/Umuzi-org/Tilde/assets/37469171/a5cd3a4d-e755-4332-9b87-16b427940a6a

2024-04-28 09:42 UTC, Sbonelo01 commented
Replaced the hover with a click - for a better UX

Uploading card-dropdown-2024-04-28_11.25.37.mov…

2024-04-29 21:13 UTC, Ngoakor12 requested changes
Unfortunately, I think this is worse experience than just showing all the reviewers...

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/6348ac06-d792-46b7-83c3-890fccc19e38)
- Why is the text styled like a button? Is none not descriptive enough? I don't think we have to have a tooltip here.

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/b96f2b33-5d14-4004-87d9-7acf74bb31a9)
- The reason the avatars were a certain distance apart was so that the initials could be visible/readable. Although this wouldn't be a problem with actual pictures, the avatars overlapping to the point of messing with the readability of initials does not work.

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/bc526ad1-ae1a-4cc5-825d-9c20b76654ea)
- I don't know about this one. We have to click and then hover just to get the reviewers? Plus the avatar circle outlines look choppy for some reason

2024-04-30 10:27 UTC, Sbonelo01 commented
@Ngoakor12 , I replaced the hover with a click. The reason for this is so that it is more intentional to see all the reviewers. 

https://github.com/Umuzi-org/Tilde/assets/37469171/1af1a51f-f2bc-4781-a7f6-47f4071d2451

2024-04-30 10:50 UTC, Sbonelo01 commented
https://github.com/Umuzi-org/Tilde/assets/37469171/0485854e-c90b-4425-afbb-940ccbaa4563

2024-04-30 12:23 UTC, kingraphaii requested changes

2024-04-30 12:23 UTC, kingraphaii commented on backend/frontend/templates/frontend/user/board/partial_card.html
Since we've gone with this tooltip style, why not have the learner emails appear all at once with the avatars on the dropdown?

Like with small side by side flex items.

2024-04-30 12:44 UTC, Ngoakor12 commented on backend/frontend/templates/frontend/user/board/partial_card.html
@kingraphaii I agree. Clicking or hovering is not an issue. The issue is having to click and hover.

@Sbonelo01 clicking should show us the emails. Whether we include the avatars too, I don't know, but we shouldn't have to both click and hover

The avatars look much better and are laid out well :slightly_smiling_face:

2024-04-30 15:24 UTC, Sbonelo01 commented
I think this introduces some clutter to the card, but the request has been addressed:

https://github.com/Umuzi-org/Tilde/assets/37469171/7a1a8383-5293-49b7-b5ce-4a1b9f983b3d

2024-04-30 16:09 UTC, kingraphaii requested changes
Much better, but we could do with a little padding, shadow and/or a border to make it float and not "add clutter" to the card(s).

2024-05-02 23:36 UTC, kingraphaii requested changes

2024-05-02 23:36 UTC, kingraphaii commented on backend/frontend/templates/frontend/user/board/partial_card.html
>                    </div>
A few issues:
- a lot of arbitrary values 😅, harder to maintain and not so easy on the eye 👀 
- I don't think the additional custom tag is necessary, let's make do with the one we have, either we make it more customizable, or use CSS to make it match what we want for the dropdown

I tried to play around with the markup and I think we can have something along this:


```html
<div x-show="isOpen"
     @click.away="isOpen = false"
     class="absolute grid gap-1 drop-shadow border rounded-md min-w-44 right-0 p-2 z-10 bg-white">
     <span class="text-xs font-medium">Reviewers</span>
  {% for reviewer in card.reviewers.all %}
    <div class="flex items-center gap-1 text-xs" title="{{ reviewer }}">
      <span class="whitespace-nowrap">{% user_avatar reviewer %}</span> 
      <span class="">{{reviewer}}</span>
    </div>
  {% endfor %}
</div>
```

2024-05-03 06:12 UTC, Sbonelo01 commented on backend/frontend/templates/frontend/user/board/partial_card.html
>                    </div>
@kingraphaii Your suggestion looks cleaner. Can we have a pairing session

2024-05-03 14:18 UTC, kingraphaii requested changes
Are your tests passing? We may have lost a template filter for code highlighting

2024-05-07 13:04 UTC, kingraphaii approved these changes

2024-05-08 11:16 UTC, Ngoakor12 requested changes
I think this is much better. Just more suggestions, let me know what you think:

![image](https://github.com/Umuzi-org/Tilde/assets/54069197/bf7d52fa-065a-4362-bc45-ce83cc53387a)

- can we just make the whole group of avatars clickable when we have more than 2 reviewers?
- I agree that the avatars are potentially cluttering the UI, especially because they don't really do anything unlike the ones in the current Tilde which link to the users' boards. Plus hovering over them still brings up the emails even though they are fully visible.
- I know we can close the pop-up by clicking away, but can we also have an explicit close icon(x) for less technical users?


...
**Side note**: Eventually I think moving to an expanding pop-up similar to what @kingraphaii  did on [this PR](https://github.com/Umuzi-org/Tilde/pull/731) might be best. I think it will look cleaner than us trying to create our own tooltip. And if I'm not mistaken that's similar to what you and Ant where planning for the redesign of cards on the current Tilde, I remember seeing it on Figma

2024-05-08 13:55 UTC, Ngoakor12 commented
I found a good example of my first point above:
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/eff9548a-e31b-4577-884b-e349047c853e)
It's the activity log on mom

2024-05-11 23:05 UTC, Sbonelo01 commented
Points addressed.
Side note noted :+1:

2024-05-13 18:52 UTC, Ngoakor12 requested changes
- For consistency's sake can we have the close icon look like the one in the screenshot of [this PR](https://github.com/Umuzi-org/Tilde/pull/725)
- My second point above was about the avatars here:
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/1063368e-6acc-4886-8528-c276bfd1c3ed)
I believe we should remove them because they don't really add anything but more clutter
- Is there any reason why we are confining the popup to the width of the card? It's not ideal especially because it makes the cancel button placement even more weird when scrolled to the right
![image](https://github.com/Umuzi-org/Tilde/assets/54069197/cfc44161-8742-45e1-b8a0-7c3eea8ac040)

2024-06-20 21:53 UTC, Sbonelo01 commented
[x] Close icon matches[ this PR](https://github.com/Umuzi-org/Tilde/pull/725)
[x] I think I remember Sheena saying the avatars should be in the drop-down. I've kept them there
[x] Width of the drop-down is contained to the width of the column, not the card

2024-06-24 22:19 UTC, kingraphaii commented
Looks better, but with longer emails, its not looking good. Will pass it to @Ngoakor12

![image](https://github.com/Umuzi-org/Tilde/assets/57295227/1cf466ab-40f1-4b02-8d31-2cd5594072e7)

2024-06-25 03:58 UTC, Ngoakor12 reviewed
Looks much better

> * [x]  I think I remember Sheena saying the avatars should be in the drop-down. I've kept them there

I disagree, mainly because I don't remember the reason for keeping them. But I'll leave that for Sheena to decide.

I believe you should open a PR branching out from `develop` since this is pulling from `develop_without_sheena` and that one already had a bunch of things merged that not apart of the `develop` branch yet

You'll pass it on to Sheena once you have the branches sorted

2024-06-25 06:11 UTC, Sbonelo01 commented
> Looks much better
> 
> > * [x]   I think I remember Sheena saying the avatars should be in the drop-down. I've kept them there
> 
> * I disagree, mainly because I don't remember the reason for keeping them. But I'll leave that for Sheena to decide.
> * I believe you should open a PR branching out from `develop` since this is pulling from `develop_without_sheena` and that one already had a bunch of things merged that not apart of the `develop` branch yet
> 
> You'll pass it on to Sheena once you have the branches sorted

Regarding Avatars. See the message to Themba in this reply: https://umuzi-projects.monday.com/boards/1274815998/pulses/1387241235/posts/214035695

I will update the branches

2024-06-25 14:28 UTC, closed without merging