Cleanup/remove unused header components
Umuzi-org/Tilde pull request #734
Opened 2024-05-05 12:38 UTC by kingraphaii

Related issues: [please specify]

## Description:

- removed the tailwind logo

- remove the "Dashboard" and "Team" link and added a link to "Teams".

- removed the notification bell icon from the top right

- removed the "settings" item from the menu

- removed the "profile" item from the menu

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested new or existing tests and made sure that they pass

2024-05-05 15:42 UTC, Ngoakor12 requested changes

2024-05-05 15:42 UTC, Ngoakor12 commented on backend/frontend/templates/frontend/partial_logged_in_main_header.html
> +                    href="{% url 'user_board' user.pk %}"
Your Board link is linking to the wrong user. It should link to the request user's board instead.

2024-05-05 15:42 UTC, Ngoakor12 commented on backend/frontend/templates/frontend/partial_logged_in_main_header.html
> +              <span class="text-white">Tilde</span>
Bolder text to differentiate it from the other link?

2024-05-05 15:49 UTC, Ngoakor12 commented
Also, the teams link should probably show that it's currently active when we're on `/users_and_teams_nav` page

2024-05-05 19:45 UTC, kingraphaii commented
> Also, the teams link should probably show that it's currently active when we're on `/users_and_teams_nav` page

That would be nice, but holding this off for now as this was mainly meant to cleanup

2024-05-06 14:43 UTC, Ngoakor12 commented
The active page link is only highlighted for bigger screens, not for smaller screens

2024-05-07 06:11 UTC, Ngoakor12 approved these changes

2024-05-07 06:11 UTC, merged