Bundle activity logging
Umuzi-org/Tilde pull request #762
Opened 2024-07-14 11:57 UTC by kingraphaii

Related issues: [please specify]

## Description:

Tracks when a bundle is claimed, unclaimed, when time is added, expired, completed.

## Screenshots/videos

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested new or existing tests and made sure that they pass

2024-07-15 15:18 UTC, Ngoakor12 reviewed
Getting this when going to the unclaimed bundles page:

```
Traceback (most recent call last):
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/frontend/views.py", line 910, in project_review_coordination_unclaimed
    ProjectReviewBundleClaim.deactivate_expired_claims()
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/project_review_coordination/models.py", line 131, in deactivate_expired_claims
    expired_claim_ids = list(expired_claims.values_list("pk", flat=True))
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 180, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1143, in execute_sql
    sql, params = self.as_sql()
  File "/home/ngoako/Desktop/code/umuzi/Tilde/backend/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 542, in as_sql
    raise TransactionManagementError('select_for_update cannot be used outside of a transaction.')
django.db.transaction.TransactionManagementError: select_for_update cannot be used outside of a transaction.
[Tilde-backend] [2024-07-15 15:14:27] ERROR [django.server:157] "GET /project_review_coordination/unclaimed/ HTTP/1.1" 500 122526
```

Maybe it's todo with my existing claims. commenting out `ProjectReviewBundleClaim.deactivate_expired_claims()` in views helped

2024-07-16 12:04 UTC, Ngoakor12 approved these changes

2024-07-19 09:07 UTC, sheenarbw reviewed
The dramatiq actor seems to have been created because a different TODO note was misunderstood. Also, the actor is being called like a normal funciton so its not actually using dramatiq.

Rather just write simple code here

2024-07-19 09:07 UTC, sheenarbw commented on backend/frontend/views.py
> -    )  # TODO: This should be in a cron job or dramatiq task
I think this TODO was misunderstood. We should still deactivate expired claims in a cron job or something instead of in the view. So the TODO should be put back

2024-07-19 09:07 UTC, sheenarbw commented on backend/project_review_coordination/models.py
> +        log_expired_bundle_claims(claim_ids=expired_claim_ids)
This just calls the thing like a normal function. It doesn't use a seperate process at all.

Also. It shouldn't. Thois was misunderstood.

Rather:

```
def expire_claim(self): <--- not a class method. This is an instance method
    self.is_active = False
    log_bundle_expired(self)
```

Or if you do want to do it in bulk:

```
    @classmethod
    def deactivate_expired_claims(cls, by_timestamp=None):
        if not by_timestamp:
            by_timestamp = timezone.now()

        expired_claims = cls.objects.filter(
            due_timestamp__lt=by_timestamp, is_active=True
        )

        expired_claim_ids = list(expired_claims.values_list("pk", flat=True))

        if not expired_claim_ids:
            return

        expired_claims.update(
            is_active=False
        )  # TODO: This should be in a cron job or dramatiq task

       for claim in expired_claims:
                log_bundle_expired(claim)
```

2024-07-19 09:07 UTC, sheenarbw commented on backend/frontend/views.py
> -    )  # TODO: This should be in a cron job or dramatiq task
The TODO here is basically saying that this functionality is being executed in a weird place. It's been refactored but it is still being exectured from a view.

You dont need to fix this TODO for now. It's a different issue.

2024-07-23 13:41 UTC, Ngoakor12 approved these changes

2024-07-29 09:58 UTC, sheenarbw reviewed
small change needed. I think reading the logs will be confusing unless we make the names a bit more verbose

2024-07-29 09:58 UTC, sheenarbw commented on backend/project_review_coordination/activity_log_creators.py
> +BUNDLE_CLAIMED = "BUNDLE_CLAIMED"
one little thing I didnt notice:

TIME_ADDED is inconsistent with the other names here.

Also it would be good to make sure that the strings are very descriptive just so it makes sense when people read them. Eg 

```
BUNDLE_CLAIMED = "PROJECT_REVIEW_BUNDLE_CLAIMED"
```

Otherwise when we see a log of all the different things a person did we would need to dig in the code to see what the words mean. This stuff should make sense to new people using Tilde who dont have access to the code

2024-07-29 09:58 UTC, sheenarbw commented on backend/project_review_coordination/models.py
> +            return
Why do you have this check?Is it more efficient somehow?

If there aren't any claims then expired_claims would be empty so it would be like saying:

```
for claim in []:
    claim.expire_claim()
```

In other words, it looks to me that the following 2 code segments do exactly the same thing:

```
if not expired_claims.exists():
            return

for claim in expired_claims:
            claim.expire_claim()
```

```
# if not expired_claims.exists():   removed these because they dont do anything
#            return

for claim in expired_claims:
            claim.expire_claim()
```

If there is a reason for it, I'm curious what it is.

2024-07-30 08:56 UTC, Ngoakor12 requested changes

2024-07-30 08:56 UTC, Ngoakor12 commented on backend/project_review_coordination/activity_log_creators.py
> +TIME_ADDED = "PROJECT_REVIEW_BUNDLE_TIME_ADDED"
I think Sheena was referring to "TIME_ADDED" not starting with "BUNDLE_" with her inconsistency comment.

2024-07-30 14:20 UTC, Ngoakor12 approved these changes

2026-05-29 06:06 UTC, closed without merging