Make project and topic page look good
Umuzi-org/Tilde pull request #763
Opened 2024-07-15 01:43 UTC by Sbonelo01

Related issues: https://umuzi-projects.monday.com/boards/1274815998/pulses/1437816996

Note: https://umuzi-projects.monday.com/boards/1274815998/pulses/1437816996#:~:text=Try%20not%20to,with%20each%20other.

## Screenshots/videos

https://github.com/Umuzi-org/Tilde/assets/37469171/2d1acf02-f9bf-4980-be85-ad5a972fb49b

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested new or existing tests and made sure that they pass

2024-07-15 14:07 UTC, Ngoakor12 requested changes
Think it looks good :)

Things to look at:
- The user avatars don't have tooltips anymore
- The cursor changes to a pointer when hovering section's body even though it's not clickable. That looks strange and misleading to me.
- Look out for long project details on mobile screens also

2024-07-22 13:29 UTC, Ngoakor12 requested changes
There's still some overlay of elements on smaller screens:
![image](https://github.com/user-attachments/assets/69283979-08fc-498e-815d-1e9be4694d5e)


Perhaps leave the icon without the "View more/less" text?

2024-07-22 13:29 UTC, Ngoakor12 commented on backend/frontend/templatetags/custom_tags.py
> +
Do we still need to do this? We can access the user instances to pass on the template just like we talked about on Slack or how it currently works in develop

2024-07-25 04:46 UTC, Sbonelo01 commented
> There's still some overlay of elements on smaller screens: ![image](https://private-user-images.githubusercontent.com/54069197/350977192-69283979-08fc-498e-815d-1e9be4694d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODI5MjYsIm5iZiI6MTcyMTg4MjYyNiwicGF0aCI6Ii81NDA2OTE5Ny8zNTA5NzcxOTItNjkyODM5NzktMDhmYy00OThlLTgxNWQtMWU5YmU0Njk0ZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA0NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNjJjYzBiYzg3OWI4MDBmNjZiMTZkNzkyZDQ0NDVmN2ZhZTZjNGU1NTY4NmQ3MjU0NDM2ZGZhMDdiNWRiZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzhZ8pfbQ3Le8keiv6mD7fRFDsTM-r9IhNir2Lpy4So)
> 
> Perhaps leave the icon without the "View more/less" text?

![scroll-bar-css](https://github.com/user-attachments/assets/4dda0ed7-95d5-4679-8cfb-4d8c4c4c128a)
![desktop-details-page](https://github.com/user-attachments/assets/ecd16139-8577-4901-a7aa-ef027c3e597a)
![tablet-details-page](https://github.com/user-attachments/assets/3b3af6b6-5d98-4152-a084-9fb77df509fb)
![mobile-details-page](https://github.com/user-attachments/assets/99436554-d160-4a7c-a11c-7bcc326c7330)

2024-07-25 11:48 UTC, Ngoakor12 requested changes
Previous changes addressed.

Unfortunately, I picked up some more issues:

![image](https://github.com/user-attachments/assets/88eb03e2-de3e-4ebf-a633-8b63e3a528eb)
- Adding both the email and avatar for assignees messes with the alignment of the left side and right side. E.g. what is None for?

Also something I just realised, maybe you disagree:
![image](https://github.com/user-attachments/assets/a0835f50-1024-4e79-9aa1-4973359465b7)

- Does the content button or link need to be at the bottom where we have to scroll all the way down? Can it not fit somewhere higher up?

![image](https://github.com/user-attachments/assets/c5db1d82-6b78-486c-8db5-bebdcc5dba74)

- It looks like the "Reviews" section heading is missing some padding, top and left

- Also not sure about the inline alignment of the reviewer and their reviews. Making the reviewer name as prominent as the actual review when we are looking at a list of reviews seems off, hierarchy-wise :shrug:

2024-07-25 12:56 UTC, Sbonelo01 commented
- Adding both the email and avatar for assignees messes with the alignment of the left side and right side

> That was pushed by mistake. Thanks for pointing it out

- Does the content button or link need to be at the bottom where we have to scroll all the way down? Can it not fit somewhere higher up?

> I see your point. But I think placing the buttons there might encourage learners to not look at repo details section. Ideally learners should also look at the PR reviews before making a Tilde review.

- It looks like the "Reviews" section heading is missing some padding, top and left

> Resolved

- Also not sure about the inline alignment of the reviewer and their reviews. Making the reviewer name as prominent as the actual review when we are looking at a list of reviews seems off, hierarchy-wise

> I agree. Resolved.

@Ngoakor12

2024-07-25 13:24 UTC, Ngoakor12 approved these changes

2024-07-29 09:45 UTC, sheenarbw approved these changes

2024-07-29 09:45 UTC, merged